export type LessonContentByDailyTarget = {
  demoMode?: "minimal_pairs" | "examples_only";
  demonstrationPairs?: { closed: string; target: string }[];
  demonstrationExamples?: string[];
  contrastiveLine2: string[];
  contrastiveLine3: string[];
  sentences: string[];
  dictatedWords: string[];
  dictatedSentences: string[];
  comprehensionQuestions: { question: string; questionType: string }[];
  heartWordsPreviewedThisLesson: string[];
  heartWordsAssumedKnown: string[];
  vocabulary: string[];
  mockPassageText: string;
  mockPassageTitle: string;
  fullAuditPassageText?: string;
  fullAuditPassageTitle?: string;
};

const sharedHeartWordsPreviewedThisLesson = ["said", "was", "they"];
const sharedHeartWordsAssumedKnown = ["I", "a", "the", "to"];

export const LESSON_CONTENT_BY_DAILY_TARGET: Record<string, LessonContentByDailyTarget> = {
  a_e: {
    demonstrationPairs: [
      { closed: "cap", target: "cape" },
      { closed: "at", target: "ate" },
      { closed: "man", target: "mane" },
      { closed: "tap", target: "tape" },
      { closed: "hat", target: "hate" },
    ],
    contrastiveLine2: ["cap", "cape", "man", "mane", "tap", "tape", "hat", "hate"],
    contrastiveLine3: ["ran", "lake", "hand", "gave", "fast", "name", "desk"],
    sentences: [
      "Dave made a cake.",
      "The cake is a gift.",
      "Jane came to the lake.",
      "They gave Jane a wave.",
      "\"I made this cake,\" said Dave.",
      "Jane is a pal to Dave.",
    ],
    dictatedWords: ["cake", "made", "lake", "game", "ran", "hand"],
    dictatedSentences: ["Dave made a cake.", "Jane came to the lake."],
    comprehensionQuestions: [
      { question: "Why did Dave make the cake?", questionType: "inference" },
      { question: "What did Jane do when Dave gave her the cake?", questionType: "literal" },
      { question: "Tell me what happened at the lake, in your own words.", questionType: "retell" },
      { question: "What is something you would make for a pal?", questionType: "personal_connection" },
    ],
    heartWordsPreviewedThisLesson: sharedHeartWordsPreviewedThisLesson,
    heartWordsAssumedKnown: sharedHeartWordsAssumedKnown,
    vocabulary: ["gift", "pal"],
    mockPassageText: `Dave has a cake. The cake is a gift to Jane. Jane came to the lake. Dave gave Jane the cake at the gate. "I made this cake," said Dave. Jane ate the cake. "This cake is the same as that cake," said Jane. They gave a big wave. Dave and Jane had fun. The lake was the best.`,
    mockPassageTitle: "Dave's Cake",
  },
  i_e: {
    demonstrationPairs: [
      { closed: "pin", target: "pine" },
      { closed: "kit", target: "kite" },
      { closed: "rid", target: "ride" },
      { closed: "fin", target: "fine" },
    ],
    contrastiveLine2: ["pin", "pine", "kit", "kite", "rid", "ride", "fin", "fine"],
    contrastiveLine3: ["ran", "lake", "hand", "bike", "fast", "mine", "desk"],
    sentences: [
      "Mike has a bike.",
      "The bike is white.",
      "Mike can ride to the lake.",
      "Jane has the same bike.",
      "\"I like this bike,\" said Mike.",
      "They ride and smile.",
    ],
    dictatedWords: ["bike", "ride", "fine", "mine", "ran", "hand"],
    dictatedSentences: ["Mike has a bike.", "Jane can ride."],
    comprehensionQuestions: [
      { question: "Why does Mike like his bike?", questionType: "inference" },
      { question: "What did Jane do at the lake?", questionType: "literal" },
      { question: "Tell me what happened at the lake in your own words.", questionType: "retell" },
      { question: "What would you ride to a lake?", questionType: "personal_connection" },
    ],
    heartWordsPreviewedThisLesson: sharedHeartWordsPreviewedThisLesson,
    heartWordsAssumedKnown: sharedHeartWordsAssumedKnown,
    vocabulary: ["bike", "ride"],
    mockPassageText: `Mike has a fine bike. The bike is white. Mike can ride the bike. Mike will ride to the lake. Jane came to ride. "I like this bike," said Mike. Jane has a bike of the same size. They ride and smile. It was a fine time at the lake.`,
    mockPassageTitle: "Mike's Bike",
  },
  o_e: {
    demonstrationPairs: [
      { closed: "not", target: "note" },
      { closed: "rob", target: "robe" },
      { closed: "cod", target: "code" },
      { closed: "hop", target: "hope" },
    ],
    contrastiveLine2: ["not", "note", "rob", "robe", "cod", "code", "hop", "hope"],
    contrastiveLine3: ["ran", "lake", "hand", "home", "fast", "mole", "desk"],
    sentences: [
      "Rose has a home.",
      "The home has a stone gate.",
      "Rose woke and rode to the cove.",
      "Cole came to the cove.",
      "\"I hope to ride,\" said Rose.",
      "A mole dug a hole.",
    ],
    dictatedWords: ["home", "rode", "note", "hope", "ran", "hand"],
    dictatedSentences: ["Rose has a home.", "Cole rode to the cove."],
    comprehensionQuestions: [
      { question: "Why did Rose go to the cove?", questionType: "inference" },
      { question: "What did the mole do?", questionType: "literal" },
      { question: "Tell me about Rose's home in your own words.", questionType: "retell" },
      { question: "What is a place you would like to visit?", questionType: "personal_connection" },
    ],
    heartWordsPreviewedThisLesson: sharedHeartWordsPreviewedThisLesson,
    heartWordsAssumedKnown: sharedHeartWordsAssumedKnown,
    vocabulary: ["stone", "cove"],
    mockPassageText: `Rose has a home. The home has a stone gate. Rose woke and rode to the cove. Cole came to the home. The cove has a big stone. Rose and Cole sat on the stone. A mole dug a hole. "I hope this home is nice," said Rose. It was a fine time at the cove.`,
    mockPassageTitle: "Rose's Home",
  },
  u_e: {
    demonstrationPairs: [
      { closed: "cub", target: "cube" },
      { closed: "tub", target: "tube" },
      { closed: "cut", target: "cute" },
      { closed: "hug", target: "huge" },
    ],
    contrastiveLine2: ["cub", "cube", "tub", "tube", "cut", "cute", "hug", "huge"],
    contrastiveLine3: ["ran", "lake", "ride", "mule", "fast", "home", "desk"],
    sentences: [
      "June has a cute mule.",
      "The mule is huge.",
      "June can ride the mule.",
      "Luke came to hum a tune.",
      "\"I like this mule,\" said June.",
      "The mule ate a prune.",
    ],
    dictatedWords: ["mule", "tune", "cute", "cube", "ran", "hand"],
    dictatedSentences: ["June has a mule.", "Luke can hum a tune."],
    comprehensionQuestions: [
      { question: "What can June's mule do?", questionType: "literal" },
      { question: "Why does June like the mule?", questionType: "inference" },
      { question: "Tell me what happened with the mule in your own words.", questionType: "retell" },
      { question: "What instrument would you want to play?", questionType: "personal_connection" },
    ],
    heartWordsPreviewedThisLesson: sharedHeartWordsPreviewedThisLesson,
    heartWordsAssumedKnown: sharedHeartWordsAssumedKnown,
    vocabulary: ["mule", "flute"],
    mockPassageText: `June has a cute mule. The mule is huge. June can ride the mule. June will hum a tune. Luke came to the mule. "I like this cute mule," said June. The mule ate a prune. They sat in the shade. Luke has a flute. It was a fine tune.`,
    mockPassageTitle: "June's Mule",
  },
  e_e: {
    demonstrationPairs: [
      { closed: "pet", target: "Pete" },
      { closed: "them", target: "theme" },
      { closed: "met", target: "mete" },
    ],
    contrastiveLine2: ["pet", "Pete", "them", "theme", "met", "mete"],
    contrastiveLine3: ["ran", "lake", "ride", "home", "scene", "Pete", "desk"],
    sentences: [
      "Pete will compete.",
      "Steve has these.",
      "The scene is set.",
      "Pete and Steve will not stop.",
      "\"I can compete,\" said Pete.",
      "They will complete the game.",
    ],
    dictatedWords: ["theme", "scene", "Pete", "these", "ran", "hand"],
    dictatedSentences: ["Pete will compete.", "Steve has a theme."],
    comprehensionQuestions: [
      { question: "What are Pete and Steve going to do?", questionType: "inference" },
      { question: "What did Steve give Pete?", questionType: "literal" },
      { question: "Tell me what happened in your own words.", questionType: "retell" },
      { question: "What is something you would like to compete in?", questionType: "personal_connection" },
    ],
    heartWordsPreviewedThisLesson: sharedHeartWordsPreviewedThisLesson,
    heartWordsAssumedKnown: sharedHeartWordsAssumedKnown,
    vocabulary: ["scene", "theme"],
    mockPassageText: `Pete will compete. Steve will compete. Pete has these. Pete has a theme. The scene is set. Pete and Steve will not stop. They will complete the game. Pete will make a plan. Steve will help Pete. "I can compete," said Pete. Steve gave Pete a note. It was a fine scene.`,
    mockPassageTitle: "Pete and Steve",
  },
  vce_mix_ai: {
    demonstrationPairs: [
      { closed: "cap", target: "cape" },
      { closed: "man", target: "mane" },
      { closed: "pin", target: "pine" },
      { closed: "rid", target: "ride" },
    ],
    contrastiveLine2: ["cap", "cape", "man", "mane", "pin", "pine", "rid", "ride"],
    contrastiveLine3: ["ran", "lake", "hand", "bike", "fast", "mine", "desk"],
    sentences: [
      "Dave has a bike.",
      "The bike is white.",
      "Mike can ride to the lake.",
      "Kate gave Dave a kite.",
      "\"I like this bike,\" said Mike.",
      "They ride and smile.",
    ],
    dictatedWords: ["cake", "bike", "ride", "made", "ran", "hand"],
    dictatedSentences: ["Dave has a bike.", "Mike can ride a mile."],
    comprehensionQuestions: [
      { question: "Why does Mike like the bike?", questionType: "inference" },
      { question: "What did Kate do?", questionType: "literal" },
      { question: "Tell me what happened at the lake in your own words.", questionType: "retell" },
      { question: "What would you like to ride?", questionType: "personal_connection" },
    ],
    heartWordsPreviewedThisLesson: sharedHeartWordsPreviewedThisLesson,
    heartWordsAssumedKnown: sharedHeartWordsAssumedKnown,
    vocabulary: ["bike", "kite"],
    mockPassageText: `Dave has a bike. Mike has a kite. The bike is white. Mike can ride to the lake. Kate came to ride. "I like this bike," said Dave. Dave gave Kate a ride. They ride and smile. It was a fine time at the lake.`,
    mockPassageTitle: "Dave's Bike",
  },
  vce_mix_oue: {
    demonstrationPairs: [
      { closed: "not", target: "note" },
      { closed: "hop", target: "hope" },
      { closed: "cub", target: "cube" },
      { closed: "cut", target: "cute" },
      { closed: "pet", target: "Pete" },
    ],
    contrastiveLine2: ["not", "note", "hop", "hope", "cub", "cube", "cut", "cute"],
    contrastiveLine3: ["ran", "home", "hand", "mule", "fast", "scene", "desk"],
    sentences: [
      "Rose has a home.",
      "June has a cute mule.",
      "The mule is huge.",
      "Pete woke and rode home.",
      "\"I hope to compete,\" said Pete.",
      "They like the scene.",
    ],
    dictatedWords: ["home", "mule", "cute", "note", "ran", "hand"],
    dictatedSentences: ["Rose has a home.", "June has a cute mule."],
    comprehensionQuestions: [
      { question: "What does June have?", questionType: "literal" },
      { question: "Why did Pete go home?", questionType: "inference" },
      { question: "Tell me what happened in your own words.", questionType: "retell" },
      { question: "What would you like to compete in?", questionType: "personal_connection" },
    ],
    heartWordsPreviewedThisLesson: sharedHeartWordsPreviewedThisLesson,
    heartWordsAssumedKnown: sharedHeartWordsAssumedKnown,
    vocabulary: ["mule", "scene"],
    mockPassageText: `Rose woke at home. June has a cute mule. The mule is huge. Pete rode the mule home. "I hope to compete," said Pete. Rose gave Pete a note. June and Pete like the mule. They sat on a stone. It was a fine scene.`,
    mockPassageTitle: "June's Mule",
  },
  vce_mix_all: {
    demonstrationPairs: [
      { closed: "cap", target: "cape" },
      { closed: "pin", target: "pine" },
      { closed: "hop", target: "hope" },
      { closed: "cub", target: "cube" },
      { closed: "pet", target: "Pete" },
    ],
    contrastiveLine2: ["cap", "cape", "pin", "pine", "hop", "hope", "cub", "cube"],
    contrastiveLine3: ["ran", "lake", "bike", "home", "mule", "Pete", "desk"],
    sentences: [
      "Dave has a bike.",
      "Rose has a cute mule.",
      "Pete rode home.",
      "June came to ride.",
      "\"I like these,\" said Pete.",
      "Mike and Dave like the lake.",
    ],
    dictatedWords: ["cake", "bike", "home", "mule", "ran", "hand"],
    dictatedSentences: ["Dave rode a bike.", "June has a mule."],
    comprehensionQuestions: [
      { question: "What can June ride?", questionType: "literal" },
      { question: "Why does Mike like the bike?", questionType: "inference" },
      { question: "Tell me what happened in your own words.", questionType: "retell" },
      { question: "What would you like to ride?", questionType: "personal_connection" },
    ],
    heartWordsPreviewedThisLesson: sharedHeartWordsPreviewedThisLesson,
    heartWordsAssumedKnown: sharedHeartWordsAssumedKnown,
    vocabulary: ["mule", "note"],
    mockPassageText: `Dave has a bike. Mike rode the bike home. Rose has a cute mule. June came to ride the mule. "I like these," said Pete. Dave gave Pete a note. Mike and June like the lake. They ride and smile. It was a fine scene.`,
    mockPassageTitle: "At the Lake",
  },
  team_ai_ay: {
    demoMode: "minimal_pairs",
    demonstrationPairs: [
      { closed: "pan", target: "pain" },
      { closed: "ran", target: "rain" },
      { closed: "man", target: "main" },
      { closed: "mad", target: "maid" },
    ],
    contrastiveLine2: ["pan", "pain", "ran", "rain", "man", "main", "mad", "maid"],
    contrastiveLine3: ["sail", "gray", "stay", "lake", "hand", "jay", "desk"],
    sentences: [
      "Gail will play in the rain.",
      "Jay had to wait all day.",
      "May and Gail paint a sail.",
      "\"The gray sail is big,\" said Jay.",
      "They stay and play.",
      "The rain is not bad.",
    ],
    dictatedWords: ["rain", "wait", "mail", "paid", "play", "stay"],
    dictatedSentences: ["Gail will play in the rain.", "Jay had to wait all day."],
    comprehensionQuestions: [
      { question: "Why did Jay have to wait?", questionType: "inference" },
      { question: "What did Gail and May paint?", questionType: "literal" },
      { question: "Tell me what happened on the rainy day.", questionType: "retell" },
      { question: "What would you paint on a rainy day?", questionType: "personal_connection" },
    ],
    heartWordsPreviewedThisLesson: sharedHeartWordsPreviewedThisLesson,
    heartWordsAssumedKnown: sharedHeartWordsAssumedKnown,
    vocabulary: ["paint", "sail"],
    mockPassageText: `Gail will play in the rain. The rain fell all day. Jay had to wait. "I see the rain," said Gail. Jay and May ran to play. They paint a sail. The sail is gray. We help Gail paint. Gail had to stay. It was a fun day.`,
    mockPassageTitle: "Gail's Rainy Day",
    fullAuditPassageText: `Gail and Jay like to play. The rain fell all day. "Stay in," said Gail. Jay had to wait a long time. May came with paint and a big pail. "Make a sail," said May. Gail made a gray sail. Jay set a snail on his sail. May made a jay with a red wing. Rain hit the pane: drip, drip, drip. "The haze is gray," said Jay. At last, the sun came up. They ran to the wet grass. The sail slid away. "That was a fun day," said May.`,
    fullAuditPassageTitle: "Gail's Rainy Day",
  },
  team_ee_ea: {
    demoMode: "minimal_pairs",
    demonstrationPairs: [
      { closed: "bed", target: "bead" },
      { closed: "men", target: "mean" },
      { closed: "set", target: "seat" },
      { closed: "ten", target: "teen" },
    ],
    contrastiveLine2: ["bed", "bead", "men", "mean", "set", "seat", "ten", "teen"],
    contrastiveLine3: ["meat", "deep", "sea", "lake", "hand", "sweet", "desk"],
    sentences: [
      "Jean and Dean see a seal at the sea.",
      "The seal can leap.",
      "Jean will feed the seal.",
      "\"I see a green reef,\" said Jean.",
      "The seal can sleep in the deep sea.",
      "It was a sweet week.",
    ],
    dictatedWords: ["see", "feet", "green", "deep", "sea", "team"],
    dictatedSentences: ["Dean can see a seal at the sea.", "The seal can leap."],
    comprehensionQuestions: [
      { question: "Why did Jean feed the seal?", questionType: "inference" },
      { question: "Where did they see the seal?", questionType: "literal" },
      { question: "Tell me what happened with the seal.", questionType: "retell" },
      { question: "What animal would you like to see?", questionType: "personal_connection" },
    ],
    heartWordsPreviewedThisLesson: sharedHeartWordsPreviewedThisLesson,
    heartWordsAssumedKnown: sharedHeartWordsAssumedKnown,
    vocabulary: ["seal", "reef"],
    mockPassageText: `We see a seal at the sea. The seal can leap. The seal ate a treat. "I see green weeds," said Jean. They feed the seal meat. The seal sleeps in the deep. We keep the seal neat. He gave the seal a bean. It was a sweet week.`,
    mockPassageTitle: "The Seal",
    fullAuditPassageText: `Jean and Dean went to the sea. They had a plan to see a seal. The sea was deep and green. "I see a green reef," said Jean. A seal swam up to eat. Jean gave the seal a treat. The seal ate meat in a tin pan. "That is a neat seal," said Dean. It can leap and dive. It made a big wave. Jean got wet feet. They sat in the sand and had a snack. "I can keep him fed," said Jean. "It must sleep in the deep sea," said Dean. The seal swam off at six. "See him speed," said Jean. The trip to the beach was sweet.`,
    fullAuditPassageTitle: "The Seal",
  },
  team_oa: {
    demoMode: "minimal_pairs",
    demonstrationPairs: [
      { closed: "got", target: "goat" },
      { closed: "cot", target: "coat" },
      { closed: "rod", target: "road" },
    ],
    contrastiveLine2: ["got", "goat", "cot", "coat", "rod", "road"],
    contrastiveLine3: ["oats", "toast", "home", "lake", "hand", "load", "desk"],
    sentences: [
      "Joan has a goat.",
      "The goat ate the oat mash.",
      "The goat ran on the road.",
      "\"That goat is fast,\" said Joan.",
      "The goat sat on a boat.",
      "It was a fine time.",
    ],
    dictatedWords: ["boat", "goat", "road", "coat", "soap", "load"],
    dictatedSentences: ["Joan has a goat.", "The goat ran on the road."],
    comprehensionQuestions: [
      { question: "Why did Joan look at the goat?", questionType: "inference" },
      { question: "What did the goat eat?", questionType: "literal" },
      { question: "Tell me what happened with Joan's goat.", questionType: "retell" },
      { question: "What animal would you like to help?", questionType: "personal_connection" },
    ],
    heartWordsPreviewedThisLesson: sharedHeartWordsPreviewedThisLesson,
    heartWordsAssumedKnown: sharedHeartWordsAssumedKnown,
    vocabulary: ["goat", "oat"],
    mockPassageText: `Joan has a goat. The goat ate the oats. The goat ran on the road. The goat had a coat. "I see a goat," said Joan. They gave the goat soap. We made goat toast. The goat sat on a boat. It was a fine day.`,
    mockPassageTitle: "Joan's Goat",
    fullAuditPassageText: `Joan has a goat at home. The goat ate oat mash. It ate much oat mash. Then the goat ran up the road. "Stop that," said Joan. The goat got in the mud. Joan got soap and a hose. Joan gave the goat a bath. The goat did not like the foam. It hid in its pen. Joan made him toast with jam. The goat had on a red coat. Joan and the goat rode in a boat on the lake. A toad sat on a log and gave a croak. The boat did float past the dock. "I like this goat," said Joan. It was a fine time at home.`,
    fullAuditPassageTitle: "Joan's Goat",
  },
  team_igh: {
    demoMode: "examples_only",
    demonstrationExamples: ["light", "night", "bright", "knight", "fight"],
    contrastiveLine2: ["light", "night", "sight", "right", "tight", "might"],
    contrastiveLine3: ["knight", "flight", "lake", "hand", "high", "desk"],
    sentences: [
      "The knight had a small light.",
      "The night was bright.",
      "The knight will fight.",
      "\"The light is bright,\" said Dwight.",
      "They might win.",
      "Dwight held the light up high.",
    ],
    dictatedWords: ["light", "night", "bright", "fight", "might", "sight"],
    dictatedSentences: ["The knight had a small light.", "The night was bright."],
    comprehensionQuestions: [
      { question: "Why did the knight need the light?", questionType: "inference" },
      { question: "What did the knight take up the hill?", questionType: "literal" },
      { question: "Tell me what happened in the bright night.", questionType: "retell" },
      { question: "What helps you see at night?", questionType: "personal_connection" },
    ],
    heartWordsPreviewedThisLesson: sharedHeartWordsPreviewedThisLesson,
    heartWordsAssumedKnown: sharedHeartWordsAssumedKnown,
    vocabulary: ["knight", "light"],
    mockPassageText: `The knight had a small light. The night was bright. The knight will fight. "I see the light," said Dwight. They might win. We held the light up high. A knight ran in the night. The light is not tight. It was a fine sight.`,
    mockPassageTitle: "The Knight",
    fullAuditPassageText: `Dwight is a knight. The knight had a small light. Dwight went up a high hill at night. The night was not bright. "I might slip on the hill," said Dwight. The wind made his light dim. The knight held the light up high. A bat came at him. The knight did not fight the bat. Dwight hid in a cave. His light lit up the cave. Dwight had figs as a snack. At last, the sun came up. The knight went home in bright sunlight. "It is a fine sight," said Dwight. Dwight slept tight all night.`,
    fullAuditPassageTitle: "The Knight",
  },
  consolidate_long_a: {
    demoMode: "minimal_pairs",
    demonstrationPairs: [
      { closed: "cap", target: "cape" },
      { closed: "man", target: "mane" },
      { closed: "pan", target: "pain" },
      { closed: "ran", target: "rain" },
    ],
    contrastiveLine2: ["cap", "cape", "man", "mane", "pan", "pain", "ran", "rain"],
    contrastiveLine3: ["play", "stay", "gray", "lane", "wait", "hand", "desk"],
    sentences: [
      "Jake made a cake at the lake.",
      "The rain fell all day.",
      "\"Stay in and play,\" said Jane.",
      "Gail had to wait in the lane.",
      "They gave May a plate.",
      "The gray paint is wet.",
    ],
    dictatedWords: ["cake", "made", "rain", "wait", "play", "day"],
    dictatedSentences: ["Jake made a cake at the lake.", "The rain fell all day."],
    comprehensionQuestions: [
      { question: "Why did Jake and Gail stay in?", questionType: "inference" },
      { question: "What did Jake and Gail make?", questionType: "literal" },
      { question: "Tell me what happened on the rainy day.", questionType: "retell" },
      { question: "What game would you play inside on a rainy day?", questionType: "personal_connection" },
    ],
    heartWordsPreviewedThisLesson: sharedHeartWordsPreviewedThisLesson,
    heartWordsAssumedKnown: sharedHeartWordsAssumedKnown,
    vocabulary: ["paint", "plate"],
    mockPassageText: `Jake made a cake. The rain fell all day. "Stay in," said Jane. Gail had to wait. They play a game at home. Jake gave May a plate. May ate the cake. "I like this game," said Gail. It was a fine day.`,
    mockPassageTitle: "The Rainy Day Cake",
    fullAuditPassageText: `Jake and Gail made a cake. The rain fell all day. "Stay in," said Jane. Jay had to wait at the gate. May came late with a pail and a cape. They gave him a plate. Jake set the cake on the plate. "It is a fine cake," said May. Gail made gray paint. They paint a game grid on a tray. Jay and May play the game. The rain came to a stop. The sun came up at last. They ran to the lake. Jake gave a wave. It was a fine day.`,
    fullAuditPassageTitle: "The Rainy Day Cake",
  },
  consolidate_long_e: {
    demoMode: "minimal_pairs",
    demonstrationPairs: [
      { closed: "pet", target: "Pete" },
      { closed: "them", target: "theme" },
      { closed: "bed", target: "bead" },
      { closed: "ten", target: "teen" },
    ],
    contrastiveLine2: ["pet", "Pete", "them", "theme", "bed", "bead", "ten", "teen"],
    contrastiveLine3: ["green", "sea", "keep", "these", "team", "hand", "desk"],
    sentences: [
      "Pete can see the green sea.",
      "Steve will eat a peach.",
      "\"This beet is sweet,\" said Pete.",
      "The team can keep the seat.",
      "Eve had a dream at home.",
      "\"Feel the heat,\" said Jean.",
    ],
    dictatedWords: ["these", "see", "green", "sea", "eat", "team"],
    dictatedSentences: ["Pete can see the green sea.", "Steve will eat a peach."],
    comprehensionQuestions: [
      { question: "Why did they feed the seal?", questionType: "inference" },
      { question: "What did Steve bring to eat?", questionType: "literal" },
      { question: "Tell me what happened at the sea.", questionType: "retell" },
      { question: "What snack would you take to the beach?", questionType: "personal_connection" },
    ],
    heartWordsPreviewedThisLesson: sharedHeartWordsPreviewedThisLesson,
    heartWordsAssumedKnown: sharedHeartWordsAssumedKnown,
    vocabulary: ["peach", "beet"],
    mockPassageText: `Pete and Steve went to the sea. "I see a green reef," said Eve. Steve had a peach to eat. A seal made a big leap. They fed the seal a treat. "See its feet," said Pete. The week was sweet.`,
    mockPassageTitle: "A Week at the Sea",
    fullAuditPassageText: `Pete and Steve went to the sea. Eve came to meet them. "I see a green reef," said Eve. The three sat in the sand. Steve had a peach to eat. Pete gave Eve a beet. "This beet is sweet," said Eve. A seal came up from the deep. It made a big leap. They fed the seal a treat. The seal kept a bean in its teeth. "See its feet," said Pete. Eve set the peach seed in a pot. They had a fine time at the sea. The week was sweet.`,
    fullAuditPassageTitle: "A Week at the Sea",
  },
  consolidate_long_o: {
    demoMode: "minimal_pairs",
    demonstrationPairs: [
      { closed: "not", target: "note" },
      { closed: "hop", target: "hope" },
      { closed: "got", target: "goat" },
      { closed: "cot", target: "coat" },
    ],
    contrastiveLine2: ["not", "note", "hop", "hope", "got", "goat", "cot", "coat"],
    contrastiveLine3: ["road", "soap", "home", "rope", "toad", "hand", "desk"],
    sentences: [
      "Joan rode home on the road.",
      "\"Tote the rope to the boat,\" said Cole.",
      "The goat woke up at home.",
      "Rose got soap and a hose.",
      "\"I hope the boat can float,\" said Joan.",
      "The toad sat on a stone.",
    ],
    dictatedWords: ["home", "note", "boat", "road", "soap", "rope"],
    dictatedSentences: ["Joan rode home on the road.", "The toad sat on a stone."],
    comprehensionQuestions: [
      { question: "Why did Cole hold the rope?", questionType: "inference" },
      { question: "What did Rose write at home?", questionType: "literal" },
      { question: "Tell me what happened on the boat ride.", questionType: "retell" },
      { question: "Where would you ride a boat?", questionType: "personal_connection" },
    ],
    heartWordsPreviewedThisLesson: sharedHeartWordsPreviewedThisLesson,
    heartWordsAssumedKnown: sharedHeartWordsAssumedKnown,
    vocabulary: ["rope", "toad"],
    mockPassageText: `Joan woke up at home. "Tote the rope to the boat," said Cole. Rose came up the road with a goat. The boat did float on the lake. A toad gave a croak. They rode home in the sun.`,
    mockPassageTitle: "The Boat Ride",
    fullAuditPassageText: `Joan and Cole woke up at home. "Tote the rope to the boat," said Cole. Joan got the soap and a hose. Rose came up the road with a goat. The goat had a red coat. Joan said, "Hop in the boat." The goat sat on a stone. A toad gave a croak on a log. The boat did float on the lake. Cole held the rope. Rose wrote a note at home. They rode home in the sun. "I hope the goat can doze," said Rose. It was a fine ride.`,
    fullAuditPassageTitle: "The Boat Ride",
  },
  consolidate_long_i: {
    demoMode: "minimal_pairs",
    demonstrationPairs: [
      { closed: "rid", target: "ride" },
      { closed: "rip", target: "ripe" },
      { closed: "fin", target: "fine" },
      { closed: "dim", target: "dime" },
    ],
    contrastiveLine2: ["rid", "ride", "rip", "ripe", "fin", "fine", "dim", "dime"],
    contrastiveLine3: ["light", "night", "bright", "time", "high", "hand", "desk"],
    sentences: [
      "Mike can ride his bike at night.",
      "The light is bright at five.",
      "\"I like this light,\" said Dwight.",
      "The kite went up high.",
      "\"Hide the dime,\" said Mike.",
      "Dwight had a fine time.",
    ],
    dictatedWords: ["ride", "time", "light", "night", "fine", "high"],
    dictatedSentences: ["Mike can ride his bike at night.", "The kite went up high."],
    comprehensionQuestions: [
      { question: "Why did Mike need the light?", questionType: "inference" },
      { question: "What was stuck in the pine?", questionType: "literal" },
      { question: "Tell me what happened on the night ride.", questionType: "retell" },
      { question: "What would you take on a night walk?", questionType: "personal_connection" },
    ],
    heartWordsPreviewedThisLesson: sharedHeartWordsPreviewedThisLesson,
    heartWordsAssumedKnown: sharedHeartWordsAssumedKnown,
    vocabulary: ["kite", "pine"],
    mockPassageText: `Mike and Dwight ride at night. The light is bright. A kite was stuck in a pine. Mike held his light up high. Dwight got the kite in time. "Nice job," said Mike. It was a fine night.`,
    mockPassageTitle: "The Night Ride",
    fullAuditPassageText: `Mike and Dwight like to ride at night. The night was fine and bright. Mike had a light on his bike. "I like this light," said Dwight. They rode up the hill in a line. A kite was stuck in a pine. Mike held his light up high. Dwight got the kite in time. "Nice job," said Mike. The pine had a fine smell. They ride a mile in the night. Mike hid a dime in his side bag. "It is mine," said Mike. Dwight slept well that night.`,
    fullAuditPassageTitle: "The Night Ride",
  },
  r_controlled_ar: {
    demoMode: "minimal_pairs",
    demonstrationPairs: [
      { closed: "cat", target: "cart" },
      { closed: "had", target: "hard" },
      { closed: "ban", target: "barn" },
      { closed: "pat", target: "part" },
    ],
    contrastiveLine2: ["cat", "cart", "had", "hard", "ban", "barn", "pat", "part"],
    contrastiveLine3: ["star", "dark", "yard", "lake", "hand", "desk", "home"],
    sentences: [
      "Carl has a car at the farm.",
      "The barn is dark and big.",
      "\"Park the car in the yard,\" said Carl.",
      "It is hard to spot a star.",
      "Mark made a tart at home.",
      "The dog can bark in the dark.",
    ],
    dictatedWords: ["car", "park", "barn", "farm", "hard", "dark"],
    dictatedSentences: ["Carl has a car at the farm.", "The barn is dark and big."],
    comprehensionQuestions: [
      { question: "How can you tell the car was hard to start?", questionType: "inference" },
      { question: "What did Carl set on the cart?", questionType: "literal" },
      { question: "Tell me what happened at the farm.", questionType: "retell" },
      { question: "What job would you do on a farm?", questionType: "personal_connection" },
    ],
    heartWordsPreviewedThisLesson: sharedHeartWordsPreviewedThisLesson,
    heartWordsAssumedKnown: sharedHeartWordsAssumedKnown,
    vocabulary: ["cart", "yard"],
    mockPassageText: `Carl woke up at the farm. The barn was still dark. "Park the cart in the yard," said Marge. Bart came up the path in a car. Carl gave him a hand. A star came up far in the dark. It was a fine start.`,
    mockPassageTitle: "A Fine Start at the Farm",
    fullAuditPassageText: `Carl woke up at the farm. The barn was still dark. "Park the cart in the yard," said Marge. Carl set a lamp on the cart. Bart came up the path in a car. "It is hard to start the car," said Bart. Carl gave him a hand. The car gave a sharp snap. At last it ran. Marge fed the hens at the gate. A star came up far in the dark. Bart said, "It is a fine farm." Carl had a big smile. It was a fine start.`,
    fullAuditPassageTitle: "A Fine Start at the Farm",
  },
  r_controlled_or: {
    demoMode: "minimal_pairs",
    demonstrationPairs: [
      { closed: "shot", target: "short" },
      { closed: "pot", target: "port" },
      { closed: "cod", target: "cord" },
      { closed: "ton", target: "torn" },
    ],
    contrastiveLine2: ["shot", "short", "pot", "port", "cod", "cord", "ton", "torn"],
    contrastiveLine3: ["storm", "horn", "north", "lake", "hand", "desk", "home"],
    sentences: [
      "The storm hit in the north.",
      "A horn went off at the fort.",
      "\"Hold the fork,\" said Norm.",
      "The corn is on the porch.",
      "Mort can sort the caps.",
      "\"Step off the cord,\" said Dot.",
    ],
    dictatedWords: ["corn", "fork", "storm", "horn", "short", "port"],
    dictatedSentences: ["The storm hit in the north.", "A horn went off at the fort."],
    comprehensionQuestions: [
      { question: "Why did Mort shut the porch gate?", questionType: "inference" },
      { question: "What did Dot get for the flag?", questionType: "literal" },
      { question: "Tell me what happened in the storm.", questionType: "retell" },
      { question: "What would you do in a big storm?", questionType: "personal_connection" },
    ],
    heartWordsPreviewedThisLesson: sharedHeartWordsPreviewedThisLesson,
    heartWordsAssumedKnown: sharedHeartWordsAssumedKnown,
    vocabulary: ["fort", "cord"],
    mockPassageText: `Norm woke up at the fort. A storm hit from the north. "Shut the porch gate," said Mort. The horn went off in the storm. At last the storm went past. It was a short storm.`,
    mockPassageTitle: "The Storm at the Fort",
    fullAuditPassageText: `Norm woke up at the fort. A storm hit from the north. The wind bent the corn. "Shut the porch gate," said Mort. Dot got the cord for the flag. The horn went off in the storm. Norm held his fork at lunch. "This corn is hot," said Dot. Mort had to sort the caps. At last the storm went past. The sun came up at last. "It was a short storm," said Norm. They sat on the porch with corn. The fort was safe and still.`,
    fullAuditPassageTitle: "The Storm at the Fort",
  },
  r_controlled_er_ir_ur: {
    demoMode: "minimal_pairs",
    demonstrationPairs: [
      { closed: "ten", target: "tern" },
      { closed: "fist", target: "first" },
      { closed: "cub", target: "curb" },
      { closed: "hut", target: "hurt" },
    ],
    contrastiveLine2: ["ten", "tern", "fist", "first", "cub", "curb", "hut", "hurt"],
    contrastiveLine3: ["her", "bird", "turn", "lake", "hand", "desk", "home"],
    sentences: [
      "The bird sat on the curb.",
      "\"Turn at the third hut,\" said Bert.",
      "Her fern is in the dirt.",
      "The girl hurt her hand.",
      "Kurt has a firm grip.",
      "\"The sun can burn the fern,\" said Gert.",
    ],
    dictatedWords: ["her", "bird", "turn", "first", "hurt", "burn"],
    dictatedSentences: ["The bird sat on the curb.", "The girl hurt her hand."],
    comprehensionQuestions: [
      { question: "Why did Fern set the pot at the curb?", questionType: "inference" },
      { question: "What did Fern feed the bird?", questionType: "literal" },
      { question: "Tell me what the bird did.", questionType: "retell" },
      { question: "What pet trick would you teach a bird?", questionType: "personal_connection" },
    ],
    heartWordsPreviewedThisLesson: sharedHeartWordsPreviewedThisLesson,
    heartWordsAssumedKnown: sharedHeartWordsAssumedKnown,
    vocabulary: ["fern", "curb"],
    mockPassageText: `Fern is a girl with a bird. The bird can chirp and turn. Kurt sat on the curb. The bird went up in a swirl. Fern fed the bird a crust. It was her best turn yet.`,
    mockPassageTitle: "The Bird That Can Twirl",
    fullAuditPassageText: `Fern is a girl with a bird. The bird can chirp and turn. "Her bird is the first to sing," said Bert. Kurt sat on the curb. The bird went up in a swirl. It came back at the third turn. "That bird can twirl," said Kurt. Fern fed the bird a crust. The bird gave a chirp. Gert had a fern in a pot. "It must not burn in the sun," said Gert. Fern set the pot at the curb. Her bird sat on her hand. It was her best turn yet.`,
    fullAuditPassageTitle: "The Bird That Can Twirl",
  },
};

export const PHASE_3_ENTRY_LESSON_CONTENT = LESSON_CONTENT_BY_DAILY_TARGET;

export type Phase3EntryLessonContent = LessonContentByDailyTarget;

export function phase3EntryLessonContentFor(dailyTargetCode: string): LessonContentByDailyTarget {
  const content = LESSON_CONTENT_BY_DAILY_TARGET[dailyTargetCode];
  if (!content) throw new Error(`No lesson content configured for ${dailyTargetCode}.`);
  return content;
}
