import type { MorphologyAnalyzerConfig } from "@/lib/literacy/morphologyAnalyzer";

export type LessonContentByDailyTarget = {
  demoMode?: "minimal_pairs" | "examples_only" | "transformation_pairs";
  demonstrationPairs?: { closed?: string; base?: string; target: string }[];
  demonstrationExamples?: string[];
  reviewWords?: string[];
  morphologyJson?: MorphologyAnalyzerConfig;
  contrastiveLine2: string[];
  contrastiveLine3: string[];
  sentences: string[];
  dictatedWords: string[];
  dictatedSentences: string[];
  comprehensionQuestions: { question: string; questionType: string }[];
  heartWordsPreviewedThisLesson: string[];
  heartWordsAssumedKnown: string[];
  vocabulary: string[];
  mockPassageText: string;
  mockPassageTitle: string;
  fullAuditPassageText?: string;
  fullAuditPassageTitle?: string;
};

const sharedHeartWordsPreviewedThisLesson = ["said", "was", "they"];
const sharedHeartWordsAssumedKnown = ["I", "a", "the", "to"];

export const LESSON_CONTENT_BY_DAILY_TARGET: Record<string, LessonContentByDailyTarget> = {
  a_e: {
    demonstrationPairs: [
      { closed: "cap", target: "cape" },
      { closed: "at", target: "ate" },
      { closed: "man", target: "mane" },
      { closed: "tap", target: "tape" },
      { closed: "hat", target: "hate" },
    ],
    contrastiveLine2: ["cap", "cape", "man", "mane", "tap", "tape", "hat", "hate"],
    contrastiveLine3: ["ran", "lake", "hand", "gave", "fast", "name", "desk"],
    sentences: [
      "Dave made a cake.",
      "The cake is a gift.",
      "Jane came to the lake.",
      "They gave Jane a wave.",
      "\"I made this cake,\" said Dave.",
      "Jane is a pal to Dave.",
    ],
    dictatedWords: ["cake", "made", "lake", "game", "ran", "hand"],
    dictatedSentences: ["Dave made a cake.", "Jane came to the lake."],
    comprehensionQuestions: [
      { question: "Why did Dave make the cake?", questionType: "inference" },
      { question: "What did Jane do when Dave gave her the cake?", questionType: "literal" },
      { question: "Tell me what happened at the lake, in your own words.", questionType: "retell" },
      { question: "What is something you would make for a pal?", questionType: "personal_connection" },
    ],
    heartWordsPreviewedThisLesson: sharedHeartWordsPreviewedThisLesson,
    heartWordsAssumedKnown: sharedHeartWordsAssumedKnown,
    vocabulary: ["gift", "pal"],
    mockPassageText: `Dave has a cake. The cake is a gift to Jane. Jane came to the lake. Dave gave Jane the cake at the gate. "I made this cake," said Dave. Jane ate the cake. "This cake is the same as that cake," said Jane. They gave a big wave. Dave and Jane had fun. The lake was the best.`,
    mockPassageTitle: "Dave's Cake",
  },
  i_e: {
    demonstrationPairs: [
      { closed: "pin", target: "pine" },
      { closed: "kit", target: "kite" },
      { closed: "rid", target: "ride" },
      { closed: "fin", target: "fine" },
    ],
    contrastiveLine2: ["pin", "pine", "kit", "kite", "rid", "ride", "fin", "fine"],
    contrastiveLine3: ["ran", "lake", "hand", "bike", "fast", "mine", "desk"],
    sentences: [
      "Mike has a bike.",
      "The bike is white.",
      "Mike can ride to the lake.",
      "Jane has the same bike.",
      "\"I like this bike,\" said Mike.",
      "They ride and smile.",
    ],
    dictatedWords: ["bike", "ride", "fine", "mine", "ran", "hand"],
    dictatedSentences: ["Mike has a bike.", "Jane can ride."],
    comprehensionQuestions: [
      { question: "Why does Mike like his bike?", questionType: "inference" },
      { question: "What did Jane do at the lake?", questionType: "literal" },
      { question: "Tell me what happened at the lake in your own words.", questionType: "retell" },
      { question: "What would you ride to a lake?", questionType: "personal_connection" },
    ],
    heartWordsPreviewedThisLesson: sharedHeartWordsPreviewedThisLesson,
    heartWordsAssumedKnown: sharedHeartWordsAssumedKnown,
    vocabulary: ["bike", "ride"],
    mockPassageText: `Mike has a fine bike. The bike is white. Mike can ride the bike. Mike will ride to the lake. Jane came to ride. "I like this bike," said Mike. Jane has a bike of the same size. They ride and smile. It was a fine time at the lake.`,
    mockPassageTitle: "Mike's Bike",
  },
  o_e: {
    demonstrationPairs: [
      { closed: "not", target: "note" },
      { closed: "rob", target: "robe" },
      { closed: "cod", target: "code" },
      { closed: "hop", target: "hope" },
    ],
    contrastiveLine2: ["not", "note", "rob", "robe", "cod", "code", "hop", "hope"],
    contrastiveLine3: ["ran", "lake", "hand", "home", "fast", "mole", "desk"],
    sentences: [
      "Rose has a home.",
      "The home has a stone gate.",
      "Rose woke and rode to the cove.",
      "Cole came to the cove.",
      "\"I hope to ride,\" said Rose.",
      "A mole dug a hole.",
    ],
    dictatedWords: ["home", "rode", "note", "hope", "ran", "hand"],
    dictatedSentences: ["Rose has a home.", "Cole rode to the cove."],
    comprehensionQuestions: [
      { question: "Why did Rose go to the cove?", questionType: "inference" },
      { question: "What did the mole do?", questionType: "literal" },
      { question: "Tell me about Rose's home in your own words.", questionType: "retell" },
      { question: "What is a place you would like to visit?", questionType: "personal_connection" },
    ],
    heartWordsPreviewedThisLesson: sharedHeartWordsPreviewedThisLesson,
    heartWordsAssumedKnown: sharedHeartWordsAssumedKnown,
    vocabulary: ["stone", "cove"],
    mockPassageText: `Rose has a home. The home has a stone gate. Rose woke and rode to the cove. Cole came to the home. The cove has a big stone. Rose and Cole sat on the stone. A mole dug a hole. "I hope this home is nice," said Rose. It was a fine time at the cove.`,
    mockPassageTitle: "Rose's Home",
  },
  u_e: {
    demonstrationPairs: [
      { closed: "cub", target: "cube" },
      { closed: "tub", target: "tube" },
      { closed: "cut", target: "cute" },
      { closed: "hug", target: "huge" },
    ],
    contrastiveLine2: ["cub", "cube", "tub", "tube", "cut", "cute", "hug", "huge"],
    contrastiveLine3: ["ran", "lake", "ride", "mule", "fast", "home", "desk"],
    sentences: [
      "June has a cute mule.",
      "The mule is huge.",
      "June can ride the mule.",
      "Luke came to hum a tune.",
      "\"I like this mule,\" said June.",
      "The mule ate a prune.",
    ],
    dictatedWords: ["mule", "tune", "cute", "cube", "ran", "hand"],
    dictatedSentences: ["June has a mule.", "Luke can hum a tune."],
    comprehensionQuestions: [
      { question: "What can June's mule do?", questionType: "literal" },
      { question: "Why does June like the mule?", questionType: "inference" },
      { question: "Tell me what happened with the mule in your own words.", questionType: "retell" },
      { question: "What instrument would you want to play?", questionType: "personal_connection" },
    ],
    heartWordsPreviewedThisLesson: sharedHeartWordsPreviewedThisLesson,
    heartWordsAssumedKnown: sharedHeartWordsAssumedKnown,
    vocabulary: ["mule", "flute"],
    mockPassageText: `June has a cute mule. The mule is huge. June can ride the mule. June will hum a tune. Luke came to the mule. "I like this cute mule," said June. The mule ate a prune. They sat in the shade. Luke has a flute. It was a fine tune.`,
    mockPassageTitle: "June's Mule",
  },
  e_e: {
    demonstrationPairs: [
      { closed: "pet", target: "Pete" },
      { closed: "them", target: "theme" },
      { closed: "met", target: "mete" },
    ],
    contrastiveLine2: ["pet", "Pete", "them", "theme", "met", "mete"],
    contrastiveLine3: ["ran", "lake", "ride", "home", "scene", "Pete", "desk"],
    sentences: [
      "Pete will compete.",
      "Steve has these.",
      "The scene is set.",
      "Pete and Steve will not stop.",
      "\"I can compete,\" said Pete.",
      "They will complete the game.",
    ],
    dictatedWords: ["theme", "scene", "Pete", "these", "ran", "hand"],
    dictatedSentences: ["Pete will compete.", "Steve has a theme."],
    comprehensionQuestions: [
      { question: "What are Pete and Steve going to do?", questionType: "inference" },
      { question: "What did Steve give Pete?", questionType: "literal" },
      { question: "Tell me what happened in your own words.", questionType: "retell" },
      { question: "What is something you would like to compete in?", questionType: "personal_connection" },
    ],
    heartWordsPreviewedThisLesson: sharedHeartWordsPreviewedThisLesson,
    heartWordsAssumedKnown: sharedHeartWordsAssumedKnown,
    vocabulary: ["scene", "theme"],
    mockPassageText: `Pete will compete. Steve will compete. Pete has these. Pete has a theme. The scene is set. Pete and Steve will not stop. They will complete the game. Pete will make a plan. Steve will help Pete. "I can compete," said Pete. Steve gave Pete a note. It was a fine scene.`,
    mockPassageTitle: "Pete and Steve",
  },
  vce_mix_ai: {
    demonstrationPairs: [
      { closed: "cap", target: "cape" },
      { closed: "man", target: "mane" },
      { closed: "pin", target: "pine" },
      { closed: "rid", target: "ride" },
    ],
    contrastiveLine2: ["cap", "cape", "man", "mane", "pin", "pine", "rid", "ride"],
    contrastiveLine3: ["ran", "lake", "hand", "bike", "fast", "mine", "desk"],
    sentences: [
      "Dave has a bike.",
      "The bike is white.",
      "Mike can ride to the lake.",
      "Kate gave Dave a kite.",
      "\"I like this bike,\" said Mike.",
      "They ride and smile.",
    ],
    dictatedWords: ["cake", "bike", "ride", "made", "ran", "hand"],
    dictatedSentences: ["Dave has a bike.", "Mike can ride a mile."],
    comprehensionQuestions: [
      { question: "Why does Mike like the bike?", questionType: "inference" },
      { question: "What did Kate do?", questionType: "literal" },
      { question: "Tell me what happened at the lake in your own words.", questionType: "retell" },
      { question: "What would you like to ride?", questionType: "personal_connection" },
    ],
    heartWordsPreviewedThisLesson: sharedHeartWordsPreviewedThisLesson,
    heartWordsAssumedKnown: sharedHeartWordsAssumedKnown,
    vocabulary: ["bike", "kite"],
    mockPassageText: `Dave has a bike. Mike has a kite. The bike is white. Mike can ride to the lake. Kate came to ride. "I like this bike," said Dave. Dave gave Kate a ride. They ride and smile. It was a fine time at the lake.`,
    mockPassageTitle: "Dave's Bike",
  },
  vce_mix_oue: {
    demonstrationPairs: [
      { closed: "not", target: "note" },
      { closed: "hop", target: "hope" },
      { closed: "cub", target: "cube" },
      { closed: "cut", target: "cute" },
      { closed: "pet", target: "Pete" },
    ],
    contrastiveLine2: ["not", "note", "hop", "hope", "cub", "cube", "cut", "cute"],
    contrastiveLine3: ["ran", "home", "hand", "mule", "fast", "scene", "desk"],
    sentences: [
      "Rose has a home.",
      "June has a cute mule.",
      "The mule is huge.",
      "Pete woke and rode home.",
      "\"I hope to compete,\" said Pete.",
      "They like the scene.",
    ],
    dictatedWords: ["home", "mule", "cute", "note", "ran", "hand"],
    dictatedSentences: ["Rose has a home.", "June has a cute mule."],
    comprehensionQuestions: [
      { question: "What does June have?", questionType: "literal" },
      { question: "Why did Pete go home?", questionType: "inference" },
      { question: "Tell me what happened in your own words.", questionType: "retell" },
      { question: "What would you like to compete in?", questionType: "personal_connection" },
    ],
    heartWordsPreviewedThisLesson: sharedHeartWordsPreviewedThisLesson,
    heartWordsAssumedKnown: sharedHeartWordsAssumedKnown,
    vocabulary: ["mule", "scene"],
    mockPassageText: `Rose woke at home. June has a cute mule. The mule is huge. Pete rode the mule home. "I hope to compete," said Pete. Rose gave Pete a note. June and Pete like the mule. They sat on a stone. It was a fine scene.`,
    mockPassageTitle: "June's Mule",
  },
  vce_mix_all: {
    demonstrationPairs: [
      { closed: "cap", target: "cape" },
      { closed: "pin", target: "pine" },
      { closed: "hop", target: "hope" },
      { closed: "cub", target: "cube" },
      { closed: "pet", target: "Pete" },
    ],
    contrastiveLine2: ["cap", "cape", "pin", "pine", "hop", "hope", "cub", "cube"],
    contrastiveLine3: ["ran", "lake", "bike", "home", "mule", "Pete", "desk"],
    sentences: [
      "Dave has a bike.",
      "Rose has a cute mule.",
      "Pete rode home.",
      "June came to ride.",
      "\"I like these,\" said Pete.",
      "Mike and Dave like the lake.",
    ],
    dictatedWords: ["cake", "bike", "home", "mule", "ran", "hand"],
    dictatedSentences: ["Dave rode a bike.", "June has a mule."],
    comprehensionQuestions: [
      { question: "What can June ride?", questionType: "literal" },
      { question: "Why does Mike like the bike?", questionType: "inference" },
      { question: "Tell me what happened in your own words.", questionType: "retell" },
      { question: "What would you like to ride?", questionType: "personal_connection" },
    ],
    heartWordsPreviewedThisLesson: sharedHeartWordsPreviewedThisLesson,
    heartWordsAssumedKnown: sharedHeartWordsAssumedKnown,
    vocabulary: ["mule", "note"],
    mockPassageText: `Dave has a bike. Mike rode the bike home. Rose has a cute mule. June came to ride the mule. "I like these," said Pete. Dave gave Pete a note. Mike and June like the lake. They ride and smile. It was a fine scene.`,
    mockPassageTitle: "At the Lake",
  },
  team_ai_ay: {
    demoMode: "minimal_pairs",
    demonstrationPairs: [
      { closed: "pan", target: "pain" },
      { closed: "ran", target: "rain" },
      { closed: "man", target: "main" },
      { closed: "mad", target: "maid" },
    ],
    contrastiveLine2: ["pan", "pain", "ran", "rain", "man", "main", "mad", "maid"],
    contrastiveLine3: ["sail", "gray", "stay", "lake", "hand", "jay", "desk"],
    sentences: [
      "Gail will play in the rain.",
      "Jay had to wait all day.",
      "May and Gail paint a sail.",
      "\"The gray sail is big,\" said Jay.",
      "They stay and play.",
      "The rain is not bad.",
    ],
    dictatedWords: ["rain", "wait", "mail", "paid", "play", "stay"],
    dictatedSentences: ["Gail will play in the rain.", "Jay had to wait all day."],
    comprehensionQuestions: [
      { question: "Why did Jay have to wait?", questionType: "inference" },
      { question: "What did Gail and May paint?", questionType: "literal" },
      { question: "Tell me what happened on the rainy day.", questionType: "retell" },
      { question: "What would you paint on a rainy day?", questionType: "personal_connection" },
    ],
    heartWordsPreviewedThisLesson: sharedHeartWordsPreviewedThisLesson,
    heartWordsAssumedKnown: sharedHeartWordsAssumedKnown,
    vocabulary: ["paint", "sail"],
    mockPassageText: `Gail will play in the rain. The rain fell all day. Jay had to wait. "I see the rain," said Gail. Jay and May ran to play. They paint a sail. The sail is gray. We help Gail paint. Gail had to stay. It was a fun day.`,
    mockPassageTitle: "Gail's Rainy Day",
    fullAuditPassageText: `Gail and Jay like to play. The rain fell all day. "Stay in," said Gail. Jay had to wait a long time. May came with paint and a big pail. "Make a sail," said May. Gail made a gray sail. Jay set a snail on his sail. May made a jay with a red wing. Rain hit the pane: drip, drip, drip. "The haze is gray," said Jay. At last, the sun came up. They ran to the wet grass. The sail slid away. "That was a fun day," said May.`,
    fullAuditPassageTitle: "Gail's Rainy Day",
  },
  team_ee_ea: {
    demoMode: "minimal_pairs",
    demonstrationPairs: [
      { closed: "bed", target: "bead" },
      { closed: "men", target: "mean" },
      { closed: "set", target: "seat" },
      { closed: "ten", target: "teen" },
    ],
    contrastiveLine2: ["bed", "bead", "men", "mean", "set", "seat", "ten", "teen"],
    contrastiveLine3: ["meat", "deep", "sea", "lake", "hand", "sweet", "desk"],
    sentences: [
      "Jean and Dean see a seal at the sea.",
      "The seal can leap.",
      "Jean will feed the seal.",
      "\"I see a green reef,\" said Jean.",
      "The seal can sleep in the deep sea.",
      "It was a sweet week.",
    ],
    dictatedWords: ["see", "feet", "green", "deep", "sea", "team"],
    dictatedSentences: ["Dean can see a seal at the sea.", "The seal can leap."],
    comprehensionQuestions: [
      { question: "Why did Jean feed the seal?", questionType: "inference" },
      { question: "Where did they see the seal?", questionType: "literal" },
      { question: "Tell me what happened with the seal.", questionType: "retell" },
      { question: "What animal would you like to see?", questionType: "personal_connection" },
    ],
    heartWordsPreviewedThisLesson: sharedHeartWordsPreviewedThisLesson,
    heartWordsAssumedKnown: sharedHeartWordsAssumedKnown,
    vocabulary: ["seal", "reef"],
    mockPassageText: `We see a seal at the sea. The seal can leap. The seal ate a treat. "I see green weeds," said Jean. They feed the seal meat. The seal sleeps in the deep. We keep the seal neat. He gave the seal a bean. It was a sweet week.`,
    mockPassageTitle: "The Seal",
    fullAuditPassageText: `Jean and Dean went to the sea. They had a plan to see a seal. The sea was deep and green. "I see a green reef," said Jean. A seal swam up to eat. Jean gave the seal a treat. The seal ate meat in a tin pan. "That is a neat seal," said Dean. It can leap and dive. It made a big wave. Jean got wet feet. They sat in the sand and had a snack. "I can keep him fed," said Jean. "It must sleep in the deep sea," said Dean. The seal swam off at six. "See him speed," said Jean. The trip to the beach was sweet.`,
    fullAuditPassageTitle: "The Seal",
  },
  team_oa: {
    demoMode: "minimal_pairs",
    demonstrationPairs: [
      { closed: "got", target: "goat" },
      { closed: "cot", target: "coat" },
      { closed: "rod", target: "road" },
    ],
    contrastiveLine2: ["got", "goat", "cot", "coat", "rod", "road"],
    contrastiveLine3: ["oats", "toast", "home", "lake", "hand", "load", "desk"],
    sentences: [
      "Joan has a goat.",
      "The goat ate the oat mash.",
      "The goat ran on the road.",
      "\"That goat is fast,\" said Joan.",
      "The goat sat on a boat.",
      "It was a fine time.",
    ],
    dictatedWords: ["boat", "goat", "road", "coat", "soap", "load"],
    dictatedSentences: ["Joan has a goat.", "The goat ran on the road."],
    comprehensionQuestions: [
      { question: "Why did Joan look at the goat?", questionType: "inference" },
      { question: "What did the goat eat?", questionType: "literal" },
      { question: "Tell me what happened with Joan's goat.", questionType: "retell" },
      { question: "What animal would you like to help?", questionType: "personal_connection" },
    ],
    heartWordsPreviewedThisLesson: sharedHeartWordsPreviewedThisLesson,
    heartWordsAssumedKnown: sharedHeartWordsAssumedKnown,
    vocabulary: ["goat", "oat"],
    mockPassageText: `Joan has a goat. The goat ate the oats. The goat ran on the road. The goat had a coat. "I see a goat," said Joan. They gave the goat soap. We made goat toast. The goat sat on a boat. It was a fine day.`,
    mockPassageTitle: "Joan's Goat",
    fullAuditPassageText: `Joan has a goat at home. The goat ate oat mash. It ate much oat mash. Then the goat ran up the road. "Stop that," said Joan. The goat got in the mud. Joan got soap and a hose. Joan gave the goat a bath. The goat did not like the foam. It hid in its pen. Joan made him toast with jam. The goat had on a red coat. Joan and the goat rode in a boat on the lake. A toad sat on a log and gave a croak. The boat did float past the dock. "I like this goat," said Joan. It was a fine time at home.`,
    fullAuditPassageTitle: "Joan's Goat",
  },
  team_igh: {
    demoMode: "examples_only",
    demonstrationExamples: ["light", "night", "bright", "knight", "fight"],
    contrastiveLine2: ["light", "night", "sight", "right", "tight", "might"],
    contrastiveLine3: ["knight", "flight", "lake", "hand", "high", "desk"],
    sentences: [
      "The knight had a small light.",
      "The night was bright.",
      "The knight will fight.",
      "\"The light is bright,\" said Dwight.",
      "They might win.",
      "Dwight held the light up high.",
    ],
    dictatedWords: ["light", "night", "bright", "fight", "might", "sight"],
    dictatedSentences: ["The knight had a small light.", "The night was bright."],
    comprehensionQuestions: [
      { question: "Why did the knight need the light?", questionType: "inference" },
      { question: "What did the knight take up the hill?", questionType: "literal" },
      { question: "Tell me what happened in the bright night.", questionType: "retell" },
      { question: "What helps you see at night?", questionType: "personal_connection" },
    ],
    heartWordsPreviewedThisLesson: sharedHeartWordsPreviewedThisLesson,
    heartWordsAssumedKnown: sharedHeartWordsAssumedKnown,
    vocabulary: ["knight", "light"],
    mockPassageText: `The knight had a small light. The night was bright. The knight will fight. "I see the light," said Dwight. They might win. We held the light up high. A knight ran in the night. The light is not tight. It was a fine sight.`,
    mockPassageTitle: "The Knight",
    fullAuditPassageText: `Dwight is a knight. The knight had a small light. Dwight went up a high hill at night. The night was not bright. "I might slip on the hill," said Dwight. The wind made his light dim. The knight held the light up high. A bat came at him. The knight did not fight the bat. Dwight hid in a cave. His light lit up the cave. Dwight had figs as a snack. At last, the sun came up. The knight went home in bright sunlight. "It is a fine sight," said Dwight. Dwight slept tight all night.`,
    fullAuditPassageTitle: "The Knight",
  },
  consolidate_long_a: {
    demoMode: "minimal_pairs",
    demonstrationPairs: [
      { closed: "cap", target: "cape" },
      { closed: "man", target: "mane" },
      { closed: "pan", target: "pain" },
      { closed: "ran", target: "rain" },
    ],
    contrastiveLine2: ["cap", "cape", "man", "mane", "pan", "pain", "ran", "rain"],
    contrastiveLine3: ["play", "stay", "gray", "lane", "wait", "hand", "desk"],
    sentences: [
      "Jake made a cake at the lake.",
      "The rain fell all day.",
      "\"Stay in and play,\" said Jane.",
      "Gail had to wait in the lane.",
      "They gave May a plate.",
      "The gray paint is wet.",
    ],
    dictatedWords: ["cake", "made", "rain", "wait", "play", "day"],
    dictatedSentences: ["Jake made a cake at the lake.", "The rain fell all day."],
    comprehensionQuestions: [
      { question: "Why did Jake and Gail stay in?", questionType: "inference" },
      { question: "What did Jake and Gail make?", questionType: "literal" },
      { question: "Tell me what happened on the rainy day.", questionType: "retell" },
      { question: "What game would you play inside on a rainy day?", questionType: "personal_connection" },
    ],
    heartWordsPreviewedThisLesson: sharedHeartWordsPreviewedThisLesson,
    heartWordsAssumedKnown: sharedHeartWordsAssumedKnown,
    vocabulary: ["paint", "plate"],
    mockPassageText: `Jake made a cake. The rain fell all day. "Stay in," said Jane. Gail had to wait. They play a game at home. Jake gave May a plate. May ate the cake. "I like this game," said Gail. It was a fine day.`,
    mockPassageTitle: "The Rainy Day Cake",
    fullAuditPassageText: `Jake and Gail made a cake. The rain fell all day. "Stay in," said Jane. Jay had to wait at the gate. May came late with a pail and a cape. They gave him a plate. Jake set the cake on the plate. "It is a fine cake," said May. Gail made gray paint. They paint a game grid on a tray. Jay and May play the game. The rain came to a stop. The sun came up at last. They ran to the lake. Jake gave a wave. It was a fine day.`,
    fullAuditPassageTitle: "The Rainy Day Cake",
  },
  consolidate_long_e: {
    demoMode: "minimal_pairs",
    demonstrationPairs: [
      { closed: "pet", target: "Pete" },
      { closed: "them", target: "theme" },
      { closed: "bed", target: "bead" },
      { closed: "ten", target: "teen" },
    ],
    contrastiveLine2: ["pet", "Pete", "them", "theme", "bed", "bead", "ten", "teen"],
    contrastiveLine3: ["green", "sea", "keep", "these", "team", "hand", "desk"],
    sentences: [
      "Pete can see the green sea.",
      "Steve will eat a peach.",
      "\"This beet is sweet,\" said Pete.",
      "The team can keep the seat.",
      "Eve had a dream at home.",
      "\"Feel the heat,\" said Jean.",
    ],
    dictatedWords: ["these", "see", "green", "sea", "eat", "team"],
    dictatedSentences: ["Pete can see the green sea.", "Steve will eat a peach."],
    comprehensionQuestions: [
      { question: "Why did they feed the seal?", questionType: "inference" },
      { question: "What did Steve bring to eat?", questionType: "literal" },
      { question: "Tell me what happened at the sea.", questionType: "retell" },
      { question: "What snack would you take to the beach?", questionType: "personal_connection" },
    ],
    heartWordsPreviewedThisLesson: sharedHeartWordsPreviewedThisLesson,
    heartWordsAssumedKnown: sharedHeartWordsAssumedKnown,
    vocabulary: ["peach", "beet"],
    mockPassageText: `Pete and Steve went to the sea. "I see a green reef," said Eve. Steve had a peach to eat. A seal made a big leap. They fed the seal a treat. "See its feet," said Pete. The week was sweet.`,
    mockPassageTitle: "A Week at the Sea",
    fullAuditPassageText: `Pete and Steve went to the sea. Eve came to meet them. "I see a green reef," said Eve. The three sat in the sand. Steve had a peach to eat. Pete gave Eve a beet. "This beet is sweet," said Eve. A seal came up from the deep. It made a big leap. They fed the seal a treat. The seal kept a bean in its teeth. "See its feet," said Pete. Eve set the peach seed in a pot. They had a fine time at the sea. The week was sweet.`,
    fullAuditPassageTitle: "A Week at the Sea",
  },
  consolidate_long_o: {
    demoMode: "minimal_pairs",
    demonstrationPairs: [
      { closed: "not", target: "note" },
      { closed: "hop", target: "hope" },
      { closed: "got", target: "goat" },
      { closed: "cot", target: "coat" },
    ],
    contrastiveLine2: ["not", "note", "hop", "hope", "got", "goat", "cot", "coat"],
    contrastiveLine3: ["road", "soap", "home", "rope", "toad", "hand", "desk"],
    sentences: [
      "Joan rode home on the road.",
      "\"Tote the rope to the boat,\" said Cole.",
      "The goat woke up at home.",
      "Rose got soap and a hose.",
      "\"I hope the boat can float,\" said Joan.",
      "The toad sat on a stone.",
    ],
    dictatedWords: ["home", "note", "boat", "road", "soap", "rope"],
    dictatedSentences: ["Joan rode home on the road.", "The toad sat on a stone."],
    comprehensionQuestions: [
      { question: "Why did Cole hold the rope?", questionType: "inference" },
      { question: "What did Rose write at home?", questionType: "literal" },
      { question: "Tell me what happened on the boat ride.", questionType: "retell" },
      { question: "Where would you ride a boat?", questionType: "personal_connection" },
    ],
    heartWordsPreviewedThisLesson: sharedHeartWordsPreviewedThisLesson,
    heartWordsAssumedKnown: sharedHeartWordsAssumedKnown,
    vocabulary: ["rope", "toad"],
    mockPassageText: `Joan woke up at home. "Tote the rope to the boat," said Cole. Rose came up the road with a goat. The boat did float on the lake. A toad gave a croak. They rode home in the sun.`,
    mockPassageTitle: "The Boat Ride",
    fullAuditPassageText: `Joan and Cole woke up at home. "Tote the rope to the boat," said Cole. Joan got the soap and a hose. Rose came up the road with a goat. The goat had a red coat. Joan said, "Hop in the boat." The goat sat on a stone. A toad gave a croak on a log. The boat did float on the lake. Cole held the rope. Rose wrote a note at home. They rode home in the sun. "I hope the goat can doze," said Rose. It was a fine ride.`,
    fullAuditPassageTitle: "The Boat Ride",
  },
  consolidate_long_i: {
    demoMode: "minimal_pairs",
    demonstrationPairs: [
      { closed: "rid", target: "ride" },
      { closed: "rip", target: "ripe" },
      { closed: "fin", target: "fine" },
      { closed: "dim", target: "dime" },
    ],
    contrastiveLine2: ["rid", "ride", "rip", "ripe", "fin", "fine", "dim", "dime"],
    contrastiveLine3: ["light", "night", "bright", "time", "high", "hand", "desk"],
    sentences: [
      "Mike can ride his bike at night.",
      "The light is bright at five.",
      "\"I like this light,\" said Dwight.",
      "The kite went up high.",
      "\"Hide the dime,\" said Mike.",
      "Dwight had a fine time.",
    ],
    dictatedWords: ["ride", "time", "light", "night", "fine", "high"],
    dictatedSentences: ["Mike can ride his bike at night.", "The kite went up high."],
    comprehensionQuestions: [
      { question: "Why did Mike need the light?", questionType: "inference" },
      { question: "What was stuck in the pine?", questionType: "literal" },
      { question: "Tell me what happened on the night ride.", questionType: "retell" },
      { question: "What would you take on a night walk?", questionType: "personal_connection" },
    ],
    heartWordsPreviewedThisLesson: sharedHeartWordsPreviewedThisLesson,
    heartWordsAssumedKnown: sharedHeartWordsAssumedKnown,
    vocabulary: ["kite", "pine"],
    mockPassageText: `Mike and Dwight ride at night. The light is bright. A kite was stuck in a pine. Mike held his light up high. Dwight got the kite in time. "Nice job," said Mike. It was a fine night.`,
    mockPassageTitle: "The Night Ride",
    fullAuditPassageText: `Mike and Dwight like to ride at night. The night was fine and bright. Mike had a light on his bike. "I like this light," said Dwight. They rode up the hill in a line. A kite was stuck in a pine. Mike held his light up high. Dwight got the kite in time. "Nice job," said Mike. The pine had a fine smell. They ride a mile in the night. Mike hid a dime in his side bag. "It is mine," said Mike. Dwight slept well that night.`,
    fullAuditPassageTitle: "The Night Ride",
  },
  r_controlled_ar: {
    demoMode: "minimal_pairs",
    demonstrationPairs: [
      { closed: "cat", target: "cart" },
      { closed: "had", target: "hard" },
      { closed: "ban", target: "barn" },
      { closed: "pat", target: "part" },
    ],
    contrastiveLine2: ["cat", "cart", "had", "hard", "ban", "barn", "pat", "part"],
    contrastiveLine3: ["star", "dark", "yard", "lake", "hand", "desk", "home"],
    sentences: [
      "Carl has a car at the farm.",
      "The barn is dark and big.",
      "\"Park the car in the yard,\" said Carl.",
      "It is hard to spot a star.",
      "Mark made a tart at home.",
      "The dog can bark in the dark.",
    ],
    dictatedWords: ["car", "park", "barn", "farm", "hard", "dark"],
    dictatedSentences: ["Carl has a car at the farm.", "The barn is dark and big."],
    comprehensionQuestions: [
      { question: "How can you tell the car was hard to start?", questionType: "inference" },
      { question: "What did Carl set on the cart?", questionType: "literal" },
      { question: "Tell me what happened at the farm.", questionType: "retell" },
      { question: "What job would you do on a farm?", questionType: "personal_connection" },
    ],
    heartWordsPreviewedThisLesson: sharedHeartWordsPreviewedThisLesson,
    heartWordsAssumedKnown: sharedHeartWordsAssumedKnown,
    vocabulary: ["cart", "yard"],
    mockPassageText: `Carl woke up at the farm. The barn was still dark. "Park the cart in the yard," said Marge. Bart came up the path in a car. Carl gave him a hand. A star came up far in the dark. It was a fine start.`,
    mockPassageTitle: "A Fine Start at the Farm",
    fullAuditPassageText: `Carl woke up at the farm. The barn was still dark. "Park the cart in the yard," said Marge. Carl set a lamp on the cart. Bart came up the path in a car. "It is hard to start the car," said Bart. Carl gave him a hand. The car gave a sharp snap. At last it ran. Marge fed the hens at the gate. A star came up far in the dark. Bart said, "It is a fine farm." Carl had a big smile. It was a fine start.`,
    fullAuditPassageTitle: "A Fine Start at the Farm",
  },
  r_controlled_or: {
    demoMode: "minimal_pairs",
    demonstrationPairs: [
      { closed: "shot", target: "short" },
      { closed: "pot", target: "port" },
      { closed: "cod", target: "cord" },
      { closed: "ton", target: "torn" },
    ],
    contrastiveLine2: ["shot", "short", "pot", "port", "cod", "cord", "ton", "torn"],
    contrastiveLine3: ["storm", "horn", "north", "lake", "hand", "desk", "home"],
    sentences: [
      "The storm hit in the north.",
      "A horn went off at the fort.",
      "\"Hold the fork,\" said Norm.",
      "The corn is on the porch.",
      "Mort can sort the caps.",
      "\"Step off the cord,\" said Dot.",
    ],
    dictatedWords: ["corn", "fork", "storm", "horn", "short", "port"],
    dictatedSentences: ["The storm hit in the north.", "A horn went off at the fort."],
    comprehensionQuestions: [
      { question: "Why did Mort shut the porch gate?", questionType: "inference" },
      { question: "What did Dot get for the flag?", questionType: "literal" },
      { question: "Tell me what happened in the storm.", questionType: "retell" },
      { question: "What would you do in a big storm?", questionType: "personal_connection" },
    ],
    heartWordsPreviewedThisLesson: sharedHeartWordsPreviewedThisLesson,
    heartWordsAssumedKnown: sharedHeartWordsAssumedKnown,
    vocabulary: ["fort", "cord"],
    mockPassageText: `Norm woke up at the fort. A storm hit from the north. "Shut the porch gate," said Mort. The horn went off in the storm. At last the storm went past. It was a short storm.`,
    mockPassageTitle: "The Storm at the Fort",
    fullAuditPassageText: `Norm woke up at the fort. A storm hit from the north. The wind bent the corn. "Shut the porch gate," said Mort. Dot got the cord for the flag. The horn went off in the storm. Norm held his fork at lunch. "This corn is hot," said Dot. Mort had to sort the caps. At last the storm went past. The sun came up at last. "It was a short storm," said Norm. They sat on the porch with corn. The fort was safe and still.`,
    fullAuditPassageTitle: "The Storm at the Fort",
  },
  r_controlled_er_ir_ur: {
    demoMode: "minimal_pairs",
    demonstrationPairs: [
      { closed: "ten", target: "tern" },
      { closed: "fist", target: "first" },
      { closed: "cub", target: "curb" },
      { closed: "hut", target: "hurt" },
    ],
    contrastiveLine2: ["ten", "tern", "fist", "first", "cub", "curb", "hut", "hurt"],
    contrastiveLine3: ["her", "bird", "turn", "lake", "hand", "desk", "home"],
    sentences: [
      "The bird sat on the curb.",
      "\"Turn at the third hut,\" said Bert.",
      "Her fern is in the dirt.",
      "The girl hurt her hand.",
      "Kurt has a firm grip.",
      "\"The sun can burn the fern,\" said Gert.",
    ],
    dictatedWords: ["her", "bird", "turn", "first", "hurt", "burn"],
    dictatedSentences: ["The bird sat on the curb.", "The girl hurt her hand."],
    comprehensionQuestions: [
      { question: "Why did Fern set the pot at the curb?", questionType: "inference" },
      { question: "What did Fern feed the bird?", questionType: "literal" },
      { question: "Tell me what the bird did.", questionType: "retell" },
      { question: "What pet trick would you teach a bird?", questionType: "personal_connection" },
    ],
    heartWordsPreviewedThisLesson: sharedHeartWordsPreviewedThisLesson,
    heartWordsAssumedKnown: sharedHeartWordsAssumedKnown,
    vocabulary: ["fern", "curb"],
    mockPassageText: `Fern is a girl with a bird. The bird can chirp and turn. Kurt sat on the curb. The bird went up in a swirl. Fern fed the bird a crust. It was her best turn yet.`,
    mockPassageTitle: "The Bird That Can Twirl",
    fullAuditPassageText: `Fern is a girl with a bird. The bird can chirp and turn. "Her bird is the first to sing," said Bert. Kurt sat on the curb. The bird went up in a swirl. It came back at the third turn. "That bird can twirl," said Kurt. Fern fed the bird a crust. The bird gave a chirp. Gert had a fern in a pot. "It must not burn in the sun," said Gert. Fern set the pot at the curb. Her bird sat on her hand. It was her best turn yet.`,
    fullAuditPassageTitle: "The Bird That Can Twirl",
  },
  diph_oi_oy: {
    demoMode: "examples_only",
    demonstrationExamples: ["coin", "boy", "oil", "joy", "soil"],
    demonstrationPairs: [],
    contrastiveLine2: ["coin", "can", "boy", "ban", "joy", "jam", "toy", "tan"],
    contrastiveLine3: ["oil", "join", "point", "lake", "hand", "desk", "home"],
    sentences: [
      "The coin fell in the soil.",
      "\"Point at the map,\" said Roy.",
      "Joy can join the club.",
      "The boy got mud on his toy.",
      "\"Boil the egg,\" said Mom.",
      "Roy can coil the rope.",
    ],
    dictatedWords: ["coin", "boy", "oil", "joy", "soil", "toy"],
    dictatedSentences: ["The coin fell in the soil.", "Joy can join the club."],
    comprehensionQuestions: [
      { question: "Why did Roy rub oil on the coin?", questionType: "inference" },
      { question: "What did the spade hit?", questionType: "literal" },
      { question: "Tell me what happened in the dig.", questionType: "retell" },
      { question: "What would you do with a coin you dug up?", questionType: "personal_connection" },
    ],
    heartWordsPreviewedThisLesson: sharedHeartWordsPreviewedThisLesson,
    heartWordsAssumedKnown: sharedHeartWordsAssumedKnown,
    vocabulary: ["coil", "gem"],
    mockPassageText: `Roy dug a hole in the soil. His pal Joy came to dig. The spade hit a coin in the mud. Roy got oil to rub on it. "Take this coin," said Roy. Joy was glad to get it.`,
    mockPassageTitle: "The Coin in the Soil",
    fullAuditPassageText: `Roy dug a hole in the soil. His pal Joy came to dig. "Point to the spot," said Joy. The spade hit a flat lump. It was a coin in the mud. "That coin is a gem," said Joy. Roy got oil to rub on it. The oil made the coin shine. Roy made a choice. "Take this coin," said Roy. "It is a gift." Joy gave a glad yelp. The boy was glad to give it. The pals sat in the sun with the coin.`,
    fullAuditPassageTitle: "The Coin in the Soil",
  },
  diph_ou_ow: {
    demoMode: "minimal_pairs",
    demonstrationPairs: [
      { closed: "shot", target: "shout" },
      { closed: "pond", target: "pound" },
      { closed: "fond", target: "found" },
      { closed: "ton", target: "town" },
    ],
    contrastiveLine2: ["shot", "shout", "pond", "pound", "fond", "found", "ton", "town"],
    contrastiveLine3: ["out", "cow", "owl", "lake", "hand", "desk", "home"],
    sentences: [
      "The owl is out at dusk.",
      "\"Count to ten,\" said Beth.",
      "The crowd was loud in town.",
      "Scout found a round stone.",
      "\"Sit down now,\" said Beth.",
      "The clown has a gown.",
    ],
    dictatedWords: ["out", "town", "loud", "down", "found", "cow"],
    dictatedSentences: ["The owl is out at dusk.", "The crowd was loud in town."],
    comprehensionQuestions: [
      { question: "Why did Scout let out a howl?", questionType: "inference" },
      { question: "What did the clown give Scout?", questionType: "literal" },
      { question: "Tell me what happened in town.", questionType: "retell" },
      { question: "What would you do at a town fair?", questionType: "personal_connection" },
    ],
    heartWordsPreviewedThisLesson: sharedHeartWordsPreviewedThisLesson,
    heartWordsAssumedKnown: sharedHeartWordsAssumedKnown,
    vocabulary: ["crowd", "clown"],
    mockPassageText: `Scout the dog sat on the steps. A loud sound came from town. Scout let out a howl. "Calm down, Scout," said Beth. It was a crowd at the town pond. Beth went down the path with Scout.`,
    mockPassageTitle: "The Loud Sound in Town",
    fullAuditPassageText: `Scout the dog sat on the steps. A loud sound came from town. Scout let out a howl. "Calm down, Scout," said Beth. The sound got close. It was a crowd at the town pond. Beth and Scout went down the path. A clown did tricks at the pond. The crowd gave a big shout. Scout found a spot up front. The clown gave Scout a crown. Scout gave a proud howl. The crowd had fun in the sun. At last Beth went home with Scout. "That was a fun trip to town," said Beth.`,
    fullAuditPassageTitle: "The Loud Sound in Town",
  },
  oo_both: {
    demoMode: "minimal_pairs",
    demonstrationPairs: [
      { closed: "rot", target: "root" },
      { closed: "hot", target: "hoot" },
      { closed: "tot", target: "toot" },
      { closed: "hop", target: "hoop" },
    ],
    contrastiveLine2: ["rot", "root", "hot", "hoot", "tot", "toot", "hop", "hoop"],
    contrastiveLine3: ["zoo", "wood", "broom", "lake", "hand", "desk", "home"],
    sentences: [
      "The moon was still up at noon.",
      "Brook took a good look at the map.",
      "\"Set the food on the stool,\" said Boone.",
      "The boot got stuck in the mud.",
      "A duck swam in the cool pool.",
      "\"Hang the hood on the hook,\" said Brook.",
    ],
    dictatedWords: ["moon", "book", "soon", "look", "food", "good"],
    dictatedSentences: ["The moon was still up at noon.", "Brook took a good look at the map."],
    comprehensionQuestions: [
      { question: "Why did Boone shake the sand from the boot?", questionType: "inference" },
      { question: "What did Boone set on the stool?", questionType: "literal" },
      { question: "Tell me what happened on the trip.", questionType: "retell" },
      { question: "What would you pack for a trip to the wood?", questionType: "personal_connection" },
    ],
    heartWordsPreviewedThisLesson: sharedHeartWordsPreviewedThisLesson,
    heartWordsAssumedKnown: sharedHeartWordsAssumedKnown,
    vocabulary: ["stool", "hood"],
    mockPassageText: `Brook and Boone set off at noon. "Look at the brook," said Boone. Brook took a sip from a cup. Soon the moon came up. Boone shook the sand from a boot. It was a good trip.`,
    mockPassageTitle: "A Good Look at the Moon",
    fullAuditPassageText: `Brook and Boone set off at noon. The path ran past a wood. "Look at the brook," said Boone. It was cool in the shade. Brook took a sip from a cup. Boone set the food on a flat stool. A duck swam a loop in the pool. Brook had a good look at it. "That duck can zoom," said Brook. Soon the sun was gone. The moon came up white and big. Boone shook the sand from a boot. "Hang the hood on the hook," said Boone. They stood still on the path. It was a good trip.`,
    fullAuditPassageTitle: "A Good Look at the Moon",
  },
  diph_au_aw: {
    demoMode: "minimal_pairs",
    demonstrationPairs: [
      { closed: "fan", target: "fawn" },
      { closed: "pan", target: "pawn" },
    ],
    contrastiveLine2: ["fan", "fawn", "pan", "pawn", "tan", "paw", "ban", "claw"],
    contrastiveLine3: ["saw", "haul", "dawn", "lake", "hand", "desk", "home"],
    sentences: [
      "Paul saw a fawn at dawn.",
      "The hawk sat on a post.",
      "\"Draw the dog,\" said Dawn.",
      "The pup got mud on its paw.",
      "Paul can haul the straw.",
      "\"Step off the lawn,\" said Dawn.",
    ],
    dictatedWords: ["saw", "paw", "lawn", "dawn", "draw", "haul"],
    dictatedSentences: ["Paul saw a fawn at dawn.", "The hawk sat on a post."],
    comprehensionQuestions: [
      { question: "Why did Paul stand still?", questionType: "inference" },
      { question: "What did the hawk dive at?", questionType: "literal" },
      { question: "Tell me what Paul saw at dawn.", questionType: "retell" },
      { question: "What animal would you draw?", questionType: "personal_connection" },
    ],
    heartWordsPreviewedThisLesson: sharedHeartWordsPreviewedThisLesson,
    heartWordsAssumedKnown: sharedHeartWordsAssumedKnown,
    vocabulary: ["fawn", "straw"],
    mockPassageText: `Paul got up at dawn. A fawn was on the lawn. "Stand still," said Paul. The fawn gave a big yawn. Dawn had a straw hat. "I can draw the fawn," said Dawn. It was a calm dawn.`,
    mockPassageTitle: "The Fawn on the Lawn",
    fullAuditPassageText: `Paul got up at dawn. The lawn was wet and still. A fawn was on the lawn. "Stand still," said Paul. Dawn had a straw hat. The fawn gave a big yawn. It bent to chomp on the grass. A hawk sat on a post. The hawk gave a caw. Paul saw the hawk dive at the grass. The fawn ran to its mom. Dawn made a sketch on a pad. "I can draw the fawn," said Dawn. Paul gave a nod. It was a calm dawn.`,
    fullAuditPassageTitle: "The Fawn on the Lawn",
  },
  team_ow: {
    demoMode: "examples_only",
    demonstrationExamples: ["snow", "grow", "show", "low", "own"],
    demonstrationPairs: [],
    contrastiveLine2: ["snow", "snap", "grow", "grab", "show", "shop", "low", "lap"],
    contrastiveLine3: ["glow", "slow", "blow", "lake", "hand", "desk", "home"],
    sentences: [
      "The snow fell on the path.",
      "\"Show us the map,\" said Mom.",
      "The plant will grow in the sun.",
      "A crow sat on the post.",
      "The flag is low on the pole.",
      "The wind can blow the snow.",
    ],
    dictatedWords: ["snow", "grow", "show", "low", "blow", "own"],
    dictatedSentences: ["The snow fell on the path.", "The plant will grow in the sun."],
    comprehensionQuestions: [
      { question: "Why did Cole grin at the top of the hill?", questionType: "inference" },
      { question: "What did the crow sit on?", questionType: "literal" },
      { question: "Tell me what Cole and Flow did in the snow.", questionType: "retell" },
      { question: "What would you do on a day with big snow?", questionType: "personal_connection" },
    ],
    heartWordsPreviewedThisLesson: sharedHeartWordsPreviewedThisLesson,
    heartWordsAssumedKnown: sharedHeartWordsAssumedKnown,
    vocabulary: ["crow", "sled"],
    mockPassageText: `Cole got up and ran to the glass. White snow fell on the steps. Cole got his sled. His dog Flow ran at his side. The sled slid fast and low. Cole did love the snow.`,
    mockPassageTitle: "Snow on the Hill",
    fullAuditPassageText: `Cole got up and ran to the glass. White snow fell on the steps. "The hill will glow in the sun," said Mom. Cole got his hat and his sled. His dog Flow ran at his side. The hill had a low dip and a slow rise. Cole and Flow went up to the top. The sled slid fast on the snow. Flow gave a glad yip. A crow sat on a low branch. "I own this hill," said Cole with a grin. The wind made the snow blow on the path. The pals went home in the soft glow. It was a fine trip in the snow.`,
    fullAuditPassageTitle: "Snow on the Hill",
  },
  team_ew_ue: {
    demoMode: "examples_only",
    demonstrationExamples: ["new", "blue", "few", "true", "glue"],
    demonstrationPairs: [],
    contrastiveLine2: ["new", "net", "blue", "bun", "few", "fed", "true", "trip"],
    contrastiveLine3: ["grew", "clue", "chew", "lake", "hand", "desk", "home"],
    sentences: [
      "The cup is blue.",
      "Sam has a new cap.",
      "The glue is on the desk.",
      "\"That clue is true,\" said Drew.",
      "A few pups sat in the sun.",
      "\"Chew the snack well,\" said Mom.",
    ],
    dictatedWords: ["new", "blue", "few", "true", "glue", "chew"],
    dictatedSentences: ["The cup is blue.", "Sam has a new cap."],
    comprehensionQuestions: [
      { question: "How can you tell the cap was not lost for long?", questionType: "inference" },
      { question: "What did Drew spot on the box?", questionType: "literal" },
      { question: "Tell me how Drew and Sue used the clue.", questionType: "retell" },
      { question: "What would you hunt for with a clue?", questionType: "personal_connection" },
    ],
    heartWordsPreviewedThisLesson: sharedHeartWordsPreviewedThisLesson,
    heartWordsAssumedKnown: sharedHeartWordsAssumedKnown,
    vocabulary: ["clue", "stew"],
    mockPassageText: `Drew and Sue sat on the steps. "The cap is lost," said Sue. It was a new blue cap. A blue spot led them to the shed. The cap sat on a chest. "This clue is true," said Drew.`,
    mockPassageTitle: "The True Clue",
    fullAuditPassageText: `Drew and Sue sat on the steps. "The cap is lost," said Sue. It was a new blue cap. "Let us hunt," said Drew. A spot of glue was on the step. A blue spot led them to the shed. The glue on the box was still wet. "This clue is true," said Drew. Sue gave a clap. The cap sat on a chest in the shed. "It is the same blue cap," said Sue. Drew grew a big grin. They went in and had hot stew. The hunt was fun and the clue was true.`,
    fullAuditPassageTitle: "The True Clue",
  },
  team_ie_both: {
    demoMode: "examples_only",
    demonstrationExamples: ["pie", "field", "tie", "chief", "shield"],
    demonstrationPairs: [],
    contrastiveLine2: ["pie", "pin", "tie", "tin", "field", "fed", "chief", "chip"],
    contrastiveLine3: ["brief", "niece", "lie", "lake", "hand", "desk", "home"],
    sentences: [
      "The pie is on the dish.",
      "\"Tie the lace,\" said the chief.",
      "The dog ran in the field.",
      "His niece has a red kite.",
      "\"Hold the shield up,\" said Gus.",
      "The cat can lie in the sun.",
    ],
    dictatedWords: ["pie", "tie", "field", "chief", "brief", "shield"],
    dictatedSentences: ["The pie is on the dish.", "The dog ran in the field."],
    comprehensionQuestions: [
      { question: "Why did Brie hold the lid up like a shield?", questionType: "inference" },
      { question: "What did Brie have in the box?", questionType: "literal" },
      { question: "Tell me what happened with the pie.", questionType: "retell" },
      { question: "What would you bring on a trip to a field?", questionType: "personal_connection" },
    ],
    heartWordsPreviewedThisLesson: sharedHeartWordsPreviewedThisLesson,
    heartWordsAssumedKnown: sharedHeartWordsAssumedKnown,
    vocabulary: ["shield", "niece"],
    mockPassageText: `The chief and his niece Brie went to the field. Brie had a pie in a box. The chief set a mat on the grass. Brie set the pie on the mat. They cut the pie and had a fine lunch.`,
    mockPassageTitle: "The Pie in the Field",
    fullAuditPassageText: `The chief and his niece Brie went to the field. Brie had a pie in a box with a lid. The chief set a mat on the grass. The wind made the mat flip. "Hold it flat," said Brie. The chief made a brief stop to fix it. Brie set the pie on the mat. A bug came at the pie. Brie held the lid up like a shield. "That was a close call," said the chief. They cut the pie and had a fine lunch. The chief gave Brie a wide grin. It was a fine end to the trip.`,
    fullAuditPassageTitle: "The Pie in the Field",
  },
  morph_drop_e: {
    demoMode: "transformation_pairs",
    morphologyJson: { rule: "drop_e", stemPatterns: ["a_e", "i_e", "o_e", "u_e"], suffixes: ["ing", "ed", "s", "es"] },
    demonstrationPairs: [
      { base: "hope", target: "hoping" },
      { base: "make", target: "making" },
      { base: "ride", target: "riding" },
      { base: "bake", target: "baked" },
    ],
    contrastiveLine2: ["hope", "hoping", "make", "making", "ride", "riding", "bake", "baked"],
    contrastiveLine3: ["smile", "use", "skate", "lake", "hand", "desk", "home"],
    sentences: [
      "Jane is hoping to bake a cake.",
      "Mike liked the big slide.",
      "\"Mike is making a mess,\" said Jane.",
      "The dog hopes to get a bite.",
      "Jane waved at the bus.",
      "\"Use the red cup,\" said Mike.",
    ],
    dictatedWords: ["hoping", "making", "riding", "baked", "liked", "hopes"],
    dictatedSentences: ["Jane is hoping to bake a cake.", "Jane waved at the bus."],
    comprehensionQuestions: [
      { question: "Why did Jane scrape the tub?", questionType: "inference" },
      { question: "What rose up like a dome?", questionType: "literal" },
      { question: "Tell me how Jane and Mike made the cake.", questionType: "retell" },
      { question: "What would you bake with a pal?", questionType: "personal_connection" },
    ],
    heartWordsPreviewedThisLesson: sharedHeartWordsPreviewedThisLesson,
    heartWordsAssumedKnown: sharedHeartWordsAssumedKnown,
    vocabulary: ["blade", "dome"],
    mockPassageText: `Jane had a plan to bake a cake. Mike came to help. They made the mix in a tub. The cake rose up like a dome. Jane sliced it and Mike liked his slice. Making it was fun.`,
    mockPassageTitle: "Baking with Mike",
    fullAuditPassageText: `Jane had a plan to bake a cake. Mike came to help. "I am hoping it will rise," said Jane. They made the mix in a big tub. Mike was smiling at the mess. Jane scraped the tub with a flat blade. The cake baked fast in the stove. It rose up like a dome. Jane and Mike skated on the path while it baked. At last Jane sliced it. Mike liked his slice. "That is a fine cake," said Mike. Jane smiled. Making it was fun. Jane hopes to bake the next one with Mike.`,
    fullAuditPassageTitle: "Baking with Mike",
  },
  morph_double: {
    demoMode: "transformation_pairs",
    morphologyJson: { rule: "double", stemPatterns: ["closed_short_a", "closed_short_i", "closed_short_o", "closed_short_u", "closed_short_e"], suffixes: ["ing", "ed", "s", "es"] },
    reviewWords: ["lake", "home", "bike", "cube", "gate", "five"],
    demonstrationPairs: [
      { base: "run", target: "running" },
      { base: "hop", target: "hopping" },
      { base: "sit", target: "sitting" },
      { base: "hug", target: "hugged" },
    ],
    contrastiveLine2: ["run", "running", "hop", "hopping", "sit", "sitting", "hug", "hugged"],
    contrastiveLine3: ["grab", "sled", "swim", "lake", "hand", "desk", "home"],
    sentences: [
      "The dog is running up the hill.",
      "Sam grabbed his red cap.",
      "\"Stop hopping on the bed,\" said Mom.",
      "Deb is sitting on the steps.",
      "Tim hugged his pup.",
      "The pup runs to the gate.",
    ],
    dictatedWords: ["running", "hopping", "sitting", "hopped", "hugged", "runs"],
    dictatedSentences: ["The dog is running up the hill.", "Tim hugged his pup."],
    comprehensionQuestions: [
      { question: "Why did Rex stop and sit still?", questionType: "inference" },
      { question: "What was sitting on the log?", questionType: "literal" },
      { question: "Tell me what Rex did on the path.", questionType: "retell" },
      { question: "What would you name a pup?", questionType: "personal_connection" },
    ],
    heartWordsPreviewedThisLesson: sharedHeartWordsPreviewedThisLesson,
    heartWordsAssumedKnown: sharedHeartWordsAssumedKnown,
    vocabulary: ["strap", "dusk"],
    mockPassageText: `Tim has a pup. His pup is Rex. Rex was hopping at a bug. A frog was sitting on a log. The frog hopped off. Rex wagged and wagged. Rex had fun running with Tim.`,
    mockPassageTitle: "The Hopping Pup",
    fullAuditPassageText: `Tim has a pup. His pup is Rex. Rex sat at the gate at six. Tim grabbed the strap and they set off. Rex was hopping at a bug on the path. The bug zipped off in the grass. A frog was sitting on a log. Rex stopped and sat still. The frog hopped off the log and was gone. Rex wagged and wagged. "What a fine pup," said Tim. Tim patted him on the back. They jogged home in the dusk. Rex napped on his rug. Rex had fun running with Tim.`,
    fullAuditPassageTitle: "The Hopping Pup",
  },
  morph_y_to_i: {
    demoMode: "transformation_pairs",
    morphologyJson: { rule: "y_to_i", stemPatterns: ["y_long_i"], suffixes: ["ed", "es", "ing"] },
    demonstrationPairs: [
      { base: "cry", target: "cried" },
      { base: "try", target: "tried" },
      { base: "fly", target: "flies" },
      { base: "dry", target: "dries" },
    ],
    contrastiveLine2: ["cry", "cried", "try", "tried", "fly", "flies", "dry", "dries"],
    contrastiveLine3: ["spy", "sky", "shy", "lake", "hand", "desk", "home"],
    sentences: [
      "Sky tried to fly the kite.",
      "The bug flies up.",
      "Sky did not cry.",
      "Dad spied a fox in the den.",
      "The mud dries in the sun.",
      "\"Sky cries a lot,\" said Mom.",
    ],
    dictatedWords: ["cried", "tried", "flies", "dries", "cries", "crying"],
    dictatedSentences: ["Sky tried to fly the kite.", "The mud dries in the sun."],
    comprehensionQuestions: [
      { question: "How can you tell Sky kept trying?", questionType: "inference" },
      { question: "What did Dad spy in the den?", questionType: "literal" },
      { question: "Tell me how Sky got the kite to fly.", questionType: "retell" },
      { question: "What would you try to fly?", questionType: "personal_connection" },
    ],
    heartWordsPreviewedThisLesson: sharedHeartWordsPreviewedThisLesson,
    heartWordsAssumedKnown: sharedHeartWordsAssumedKnown,
    vocabulary: ["gust", "den"],
    mockPassageText: `Sky had a red kite. Sky tried to make it fly. The kite did not fly yet. Sky did not cry. Sky tried a lot. Then it flies up. Sky cried a glad cry. It was a fine try.`,
    mockPassageTitle: "Sky and the Kite",
    fullAuditPassageText: `Sky had a red kite. Sky tried to make it fly. The kite did not fly yet. Sky did not cry. Sky tried a lot. Then a gust came. The kite rose up fast. It flies! The kite flies up in the sky. Sky cried a glad cry. Dad spied the kite up on the hill. Mom came up to help. The kite dips, then flies up. They had a fine time. Sky kept trying fun tricks. The mud dries on the kite. It was a fine try.`,
    fullAuditPassageTitle: "Sky and the Kite",
  },
  morph_compare_no_change: {
    demoMode: "transformation_pairs",
    morphologyJson: {
      rule: "compare",
      stemPatterns: ["closed_short_a", "closed_short_e", "closed_short_i", "closed_short_o", "team_ow"],
      comparativeStems: ["fast", "tall", "slow", "soft", "fresh", "thick", "rich"],
      suffixes: ["er", "est"],
    },
    reviewWords: ["lake", "home", "bike", "cube", "gate", "five"],
    demonstrationPairs: [
      { base: "fast", target: "faster" },
      { base: "soft", target: "softer" },
      { base: "thick", target: "thicker" },
      { base: "slow", target: "slowest" },
      { base: "tall", target: "tallest" },
    ],
    contrastiveLine2: ["fast", "faster", "soft", "softer", "thick", "thicker", "slow", "slowest"],
    contrastiveLine3: ["tall", "taller", "fresh", "fresher", "rich", "richer"],
    sentences: [
      "The cat can run faster than the pup.",
      "The pup naps on the softer mat.",
      "The pond mud is thicker.",
      "The slug is the slowest bug.",
      "Sam has the fresher snack.",
      "That hill is the tallest.",
    ],
    dictatedWords: ["faster", "softer", "thicker", "slower", "fastest", "softest"],
    dictatedSentences: ["The cat can run faster.", "That hill is the tallest."],
    comprehensionQuestions: [
      { question: "How can you tell the cat is faster than the pup?", questionType: "inference" },
      { question: "What does the cat nap on?", questionType: "literal" },
      { question: "Tell me how Sam's pets are different.", questionType: "retell" },
      { question: "What pet would you like?", questionType: "personal_connection" },
    ],
    heartWordsPreviewedThisLesson: sharedHeartWordsPreviewedThisLesson,
    heartWordsAssumedKnown: sharedHeartWordsAssumedKnown,
    vocabulary: ["slug", "pond"],
    mockPassageText: `Sam has a cat and a pup. The pup can run fast. The cat can run faster. The cat is fastest. The pup sits on a soft mat. The cat naps on a softer mat. The softest mat is a hit.`,
    mockPassageTitle: "Sam and His Pets",
    fullAuditPassageText: `Sam has a cat and a pup. The pup can run fast. The cat can run faster. The cat is fastest. The pup sits on a soft mat. The cat naps on a softer mat. The softest mat is a hit. Sam spots a slug. The slug is slow. It gets slower. It is the slowest. Sam digs in thick mud. The pond mud is thicker. The thickest mud is a mess. At lunch, Sam has fresh ham. The next snack is fresher. Sam grins and naps in the sun.`,
    fullAuditPassageTitle: "Sam and His Pets",
  },
};

export const PHASE_3_ENTRY_LESSON_CONTENT = LESSON_CONTENT_BY_DAILY_TARGET;

export type Phase3EntryLessonContent = LessonContentByDailyTarget;

export function phase3EntryLessonContentFor(dailyTargetCode: string): LessonContentByDailyTarget {
  const content = LESSON_CONTENT_BY_DAILY_TARGET[dailyTargetCode];
  if (!content) throw new Error(`No lesson content configured for ${dailyTargetCode}.`);
  return content;
}
