export const MISCUE_TYPES = {
  CORRECT: "CORRECT",
  SUBSTITUTION: "SUBSTITUTION",
  OMISSION: "OMISSION",
  INSERTION: "INSERTION",
  SELF_CORRECTION: "SELF_CORRECTION",
  HESITATION: "HESITATION",
  REPETITION: "REPETITION",
  MISPRONUNCIATION: "MISPRONUNCIATION",
  DECODING_ERROR: "DECODING_ERROR",
  EXPECTED_DIALECT_TRANSFER: "EXPECTED_DIALECT_TRANSFER",
  UNINTELLIGIBLE: "UNINTELLIGIBLE",
} as const;

export type MiscueType = (typeof MISCUE_TYPES)[keyof typeof MISCUE_TYPES];

export const MISCUE_TYPE_VALUES = Object.values(MISCUE_TYPES);

export function isMiscueType(value: string): value is MiscueType {
  return MISCUE_TYPE_VALUES.includes(value as MiscueType);
}
