"use client";
import { useEffect, useState } from "react";
import { parentFriendlyGrowth, parentFriendlyPerformanceLevel } from "@/lib/parentFriendlyText";

export function ParentDashboardPage() {
  const [data, setData] = useState<any>(null);
  const [selectedStudentId, setSelectedStudentId] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => { (async () => { const res = await fetch("/api/parent/dashboard"); const json = await res.json(); setData(json); setLoading(false); })(); }, []);
  if (loading) return <div className="rounded-3xl bg-white p-6 shadow">Loading parent dashboard...</div>;
  if (!data) return <div className="rounded-3xl bg-white p-6 shadow">No data available.</div>;
  const selectedChild = data.children.find((child: any) => child.studentId === selectedStudentId) || data.children[0];
  return <div className="space-y-6"><div className="rounded-3xl bg-white p-6 shadow"><h1 className="text-3xl font-bold">Parent Portal</h1><p className="mt-2 text-slate-600">View your child’s latest test results, growth, and standards progress.</p></div><div className="rounded-3xl bg-white p-6 shadow"><label className="mb-2 block text-sm font-semibold text-slate-700">Student</label><select value={selectedChild?.studentId} onChange={(e)=>setSelectedStudentId(e.target.value)} className="w-full rounded-2xl border border-slate-300 px-4 py-3">{data.children.map((child: any) => <option key={child.studentId} value={child.studentId}>{child.studentName} (Grade {child.grade})</option>)}</select></div>{selectedChild && <><div className="grid gap-6 md:grid-cols-4"><Metric title="Latest Score" value={selectedChild.latestScore != null ? `${selectedChild.latestScore}%` : "N/A"} /><Metric title="Performance Level" value={selectedChild.performanceBand ? parentFriendlyPerformanceLevel(selectedChild.performanceBand) : "N/A"} /><Metric title="Growth" value={selectedChild.growth?.growthPoints != null ? `${selectedChild.growth.growthPoints >= 0 ? "+" : ""}${selectedChild.growth.growthPoints}` : "N/A"} /><Metric title="Latest Assessment" value={selectedChild.latestAssessment ?? "N/A"} /></div><div className="rounded-3xl bg-white p-6 shadow"><h2 className="text-2xl font-bold">Growth Summary</h2><p className="mt-4 text-slate-700">{parentFriendlyGrowth(selectedChild.growth?.growthPoints ?? null)}</p><button onClick={async () => { await fetch("/api/parent/email-summary", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ studentId: selectedChild.studentId }) }); alert("Summary emailed."); }} className="mt-4 rounded-2xl bg-slate-900 px-4 py-3 font-semibold text-white">Email Me This Summary</button></div><div className="rounded-3xl bg-white p-6 shadow"><h2 className="text-2xl font-bold">Standards Mastery</h2><div className="mt-5 overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="text-slate-500"><tr><th className="pb-3 pr-4">Standard</th><th className="pb-3 pr-4">Description</th><th className="pb-3 pr-4">Score</th><th className="pb-3 pr-4">Level</th></tr></thead><tbody>{selectedChild.standardsMastery.map((row: any) => <tr key={row.standardCode} className="border-t border-slate-100"><td className="py-3 pr-4 font-semibold">{row.standardCode}</td><td className="py-3 pr-4">{row.standardLabel}</td><td className="py-3 pr-4">{row.percentScore}%</td><td className="py-3 pr-4">{row.performanceBand}</td></tr>)}</tbody></table></div></div></>}</div>;
}
function Metric({ title, value }: { title: string; value: string }) { return <div className="rounded-3xl bg-white p-6 shadow"><div className="text-sm font-semibold uppercase tracking-wide text-slate-500">{title}</div><div className="mt-2 text-2xl font-bold">{value}</div></div>; }
