"use client";
import { useEffect, useMemo, useState } from "react";
import type { Question, ResponseRecord, McqQuestion, EbsrQuestion, HotTextQuestion, MultiSelectQuestion, DragDropQuestion } from "@/types";

type SubmitPayload = { isCorrect: boolean; scorePointsEarned: number; maxPoints: number; errorPattern: string; answerPayload: Record<string, unknown>; };
export function StudentTest({ currentQuestion, currentQuestionNumber, totalQuestions, history, onSubmitAnswer }: { currentQuestion: Question; currentQuestionNumber: number; totalQuestions: number; history: ResponseRecord[]; onSubmitAnswer: (payload: SubmitPayload) => Promise<void>; }) {
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [partAIndex, setPartAIndex] = useState<number | null>(null);
  const [partBIndices, setPartBIndices] = useState<number[]>([]);
  const [multiIndices, setMultiIndices] = useState<number[]>([]);
  const [dragMapping, setDragMapping] = useState<Record<string, string>>({});

  useEffect(() => {
    setPartAIndex(null); setPartBIndices([]); setMultiIndices([]);
    if (currentQuestion.type === "DRAG_DROP") {
      const initial = currentQuestion.dragItems.reduce<Record<string, string>>((acc, item) => { acc[item.id] = currentQuestion.categories[0]; return acc; }, {});
      setDragMapping(initial);
    } else setDragMapping({});
  }, [currentQuestion]);

  async function safeSubmit(payload: SubmitPayload) { if (isSubmitting) return; setIsSubmitting(true); try { await onSubmitAnswer(payload); } finally { setIsSubmitting(false); } }
  async function submitMcq(index: number) { const q = currentQuestion as McqQuestion; const isCorrect = index === q.correctIndex; await safeSubmit({ isCorrect, scorePointsEarned: isCorrect ? 1 : 0, maxPoints: 1, errorPattern: isCorrect ? "none" : "general_misread", answerPayload: { selectedIndex: index, correctIndex: q.correctIndex } }); }
  function togglePartB(index: number) { setPartBIndices((prev) => prev.includes(index) ? prev.filter((i) => i !== index) : prev.length >= 2 ? prev : [...prev, index]); }
  async function submitEbsr() { const q = currentQuestion as EbsrQuestion; if (partAIndex === null || partBIndices.length !== 2) return; const partACorrect = partAIndex === q.partACorrectIndex; const sortedStudent = [...partBIndices].sort((a,b)=>a-b); const sortedCorrect = [...q.partBCorrectIndices].sort((a,b)=>a-b); const partBCorrect = JSON.stringify(sortedStudent) === JSON.stringify(sortedCorrect); const isCorrect = partACorrect && partBCorrect; const scorePointsEarned = (partACorrect ? 1 : 0) + (partBCorrect ? 1 : 0); const errorPattern = isCorrect ? "none" : partACorrect && !partBCorrect ? "part_a_correct_but_evidence_wrong" : !partACorrect && partBCorrect ? "part_a_wrong_even_with_some_evidence_match" : "ebsr_double_miss_in_claim_and_evidence"; await safeSubmit({ isCorrect, scorePointsEarned, maxPoints: 2, errorPattern, answerPayload: { partAIndex, partBIndices, partACorrectIndex: q.partACorrectIndex, partBCorrectIndices: q.partBCorrectIndices } }); }
  async function submitHotText(index: number) { const q = currentQuestion as HotTextQuestion; const isCorrect = q.correctSpanIndices.includes(index); await safeSubmit({ isCorrect, scorePointsEarned: isCorrect ? 1 : 0, maxPoints: 1, errorPattern: isCorrect ? "none" : "selected_related_sentence_not_best_text_evidence", answerPayload: { selectedSpanIndex: index, correctSpanIndices: q.correctSpanIndices } }); }
  function toggleMulti(index: number) { setMultiIndices((prev) => prev.includes(index) ? prev.filter((i) => i !== index) : prev.length >= 2 ? prev : [...prev, index]); }
  async function submitMulti() { const q = currentQuestion as MultiSelectQuestion; if (multiIndices.length !== 2) return; const sortedStudent = [...multiIndices].sort((a,b)=>a-b); const sortedCorrect = [...q.correctIndices].sort((a,b)=>a-b); const isCorrect = JSON.stringify(sortedStudent) === JSON.stringify(sortedCorrect); await safeSubmit({ isCorrect, scorePointsEarned: isCorrect ? 1 : 0, maxPoints: 1, errorPattern: isCorrect ? "none" : "partial_or_incorrect_multi_select_combination", answerPayload: { selectedIndices: multiIndices, correctIndices: q.correctIndices } }); }
  const dragReady = useMemo(() => currentQuestion.type === "DRAG_DROP" ? currentQuestion.dragItems.every((item) => Boolean(dragMapping[item.id])) : false, [currentQuestion, dragMapping]);
  async function submitDragDrop() { const q = currentQuestion as DragDropQuestion; const itemIds = Object.keys(q.correctMapping); const correctCount = itemIds.filter((id) => dragMapping[id] === q.correctMapping[id]).length; const isCorrect = correctCount === itemIds.length; await safeSubmit({ isCorrect, scorePointsEarned: correctCount, maxPoints: itemIds.length, errorPattern: isCorrect ? "none" : correctCount > 0 ? "partially_sorted_drag_drop_categories" : "drag_drop_category_confusion", answerPayload: { mapping: dragMapping, correctMapping: q.correctMapping, correctCount } }); }

  return <div className="grid gap-6 lg:grid-cols-4"><div className="rounded-3xl bg-white p-5 shadow lg:col-span-1"><div className="mb-4"><div className="text-xs font-semibold uppercase tracking-wide text-slate-500">Assessment Delivery</div><h2 className="mt-1 text-xl font-bold">PSSA ELA Practice</h2><p className="mt-1 text-sm text-slate-600">Question {currentQuestionNumber} of {totalQuestions}</p></div><div className="mb-5 h-2 rounded-full bg-slate-200"><div className="h-2 rounded-full bg-blue-600" style={{ width: `${(currentQuestionNumber / totalQuestions) * 100}%` }} /></div><div className="text-sm text-slate-600">Skill: {currentQuestion.skill}</div><div className="text-sm text-slate-600">Format: {currentQuestion.type}</div><div className="mt-3 grid grid-cols-5 gap-2">{Array.from({ length: totalQuestions }).map((_, i) => { const q = history[i] || null; const active = i === currentQuestionNumber - 1; return <div key={i} className={`flex h-10 w-10 items-center justify-center rounded-full border text-sm font-semibold ${active ? "border-blue-600 bg-blue-600 text-white" : q ? q.isCorrect ? "border-emerald-300 bg-emerald-50 text-emerald-700" : "border-rose-300 bg-rose-50 text-rose-700" : "border-slate-200 bg-slate-50 text-slate-500"}`}>{i + 1}</div>; })}</div></div><div className="rounded-3xl bg-white p-6 shadow lg:col-span-3"><div className="mb-4 flex flex-wrap items-center gap-2 text-sm"><span className="rounded-full bg-slate-100 px-3 py-1 font-medium">{currentQuestion.type}</span><span className="rounded-full bg-blue-50 px-3 py-1 font-medium text-blue-700">{currentQuestion.skill}</span><span className="rounded-full bg-emerald-50 px-3 py-1 font-medium text-emerald-700">{currentQuestion.standardCode}</span></div><h2 className="text-2xl font-bold">{currentQuestion.passageTitle}</h2><div className="mt-4 rounded-2xl border border-slate-200 bg-slate-50 p-4 leading-7 text-slate-700">{currentQuestion.passage}</div>
  {currentQuestion.type === "MCQ" && <div className="mt-6"><h3 className="text-lg font-semibold">{(currentQuestion as McqQuestion).question}</h3><div className="mt-4 space-y-3">{(currentQuestion as McqQuestion).choices.map((choice, index) => <button key={index} onClick={() => submitMcq(index)} disabled={isSubmitting} className="block w-full rounded-2xl border border-slate-200 p-4 text-left hover:bg-slate-50 disabled:opacity-60">{choice}</button>)}</div></div>}
  {currentQuestion.type === "EBSR" && <div className="mt-6 space-y-6"><div className="rounded-2xl border border-slate-200 p-5"><div className="mb-3 text-sm font-semibold uppercase tracking-wide text-slate-500">Part A</div><h3 className="text-lg font-semibold">{(currentQuestion as EbsrQuestion).partAQuestion}</h3><div className="mt-4 space-y-3">{(currentQuestion as EbsrQuestion).partAChoices.map((choice, index) => <button key={index} onClick={() => setPartAIndex(index)} className={`block w-full rounded-2xl border p-4 text-left ${partAIndex === index ? "border-blue-600 bg-blue-50" : "border-slate-200 hover:bg-slate-50"}`}>{choice}</button>)}</div></div><div className="rounded-2xl border border-slate-200 p-5"><div className="mb-3 text-sm font-semibold uppercase tracking-wide text-slate-500">Part B</div><h3 className="text-lg font-semibold">{(currentQuestion as EbsrQuestion).partBQuestion}</h3><div className="mt-4 space-y-3">{(currentQuestion as EbsrQuestion).partBChoices.map((choice, index) => <button key={index} onClick={() => togglePartB(index)} className={`block w-full rounded-2xl border p-4 text-left ${partBIndices.includes(index) ? "border-blue-600 bg-blue-50" : "border-slate-200 hover:bg-slate-50"}`}>{choice}</button>)}</div></div><button onClick={submitEbsr} disabled={isSubmitting || partAIndex === null || partBIndices.length !== 2} className="rounded-2xl bg-blue-600 px-5 py-3 font-semibold text-white disabled:bg-slate-300">Submit EBSR Response</button></div>}
  {currentQuestion.type === "HOT_TEXT" && <div className="mt-6 rounded-2xl border border-slate-200 p-5"><div className="mb-3 text-sm font-semibold uppercase tracking-wide text-slate-500">Hot Text</div><h3 className="text-lg font-semibold">{(currentQuestion as HotTextQuestion).hotTextPrompt}</h3><div className="mt-4 space-y-3">{(currentQuestion as HotTextQuestion).selectableSpans.map((span, index) => <button key={index} onClick={() => submitHotText(index)} className="block w-full rounded-2xl border border-slate-200 p-4 text-left hover:bg-slate-50">{span}</button>)}</div></div>}
  {currentQuestion.type === "MULTI_SELECT" && <div className="mt-6 space-y-5"><div className="rounded-2xl border border-slate-200 p-5"><div className="mb-3 text-sm font-semibold uppercase tracking-wide text-slate-500">Multi-Select</div><h3 className="text-lg font-semibold">{(currentQuestion as MultiSelectQuestion).question}</h3><div className="mt-4 space-y-3">{(currentQuestion as MultiSelectQuestion).choices.map((choice, index) => <button key={index} onClick={() => toggleMulti(index)} className={`block w-full rounded-2xl border p-4 text-left ${multiIndices.includes(index) ? "border-blue-600 bg-blue-50" : "border-slate-200 hover:bg-slate-50"}`}>{choice}</button>)}</div></div><button onClick={submitMulti} disabled={isSubmitting || multiIndices.length !== 2} className="rounded-2xl bg-blue-600 px-5 py-3 font-semibold text-white disabled:bg-slate-300">Submit Multi-Select Response</button></div>}
  {currentQuestion.type === "DRAG_DROP" && <div className="mt-6 space-y-5"><div className="rounded-2xl border border-slate-200 p-5"><div className="mb-3 text-sm font-semibold uppercase tracking-wide text-slate-500">Drag and Drop</div><h3 className="text-lg font-semibold">{(currentQuestion as DragDropQuestion).dragDropPrompt}</h3><div className="mt-5 grid gap-4 md:grid-cols-2">{(currentQuestion as DragDropQuestion).dragItems.map((item) => <div key={item.id} className="rounded-2xl border border-slate-200 p-4"><div className="text-sm leading-6 text-slate-800">{item.text}</div><select value={dragMapping[item.id] || (currentQuestion as DragDropQuestion).categories[0]} onChange={(e) => setDragMapping((prev) => ({ ...prev, [item.id]: e.target.value }))} className="mt-3 w-full rounded-xl border border-slate-300 px-3 py-2 text-sm">{(currentQuestion as DragDropQuestion).categories.map((cat) => <option key={cat} value={cat}>{cat}</option>)}</select></div>)}</div></div><button onClick={submitDragDrop} disabled={isSubmitting || !dragReady} className="rounded-2xl bg-blue-600 px-5 py-3 font-semibold text-white disabled:bg-slate-300">Submit Drag-and-Drop Response</button></div>}
  </div></div>;
}
