export const DECISION_TYPES = {
  ITEM_GENERATION: "ITEM_GENERATION",
  DISTRACTOR_GENERATION: "DISTRACTOR_GENERATION",
  DISTRACTOR_CRITIC: "DISTRACTOR_CRITIC",
  LESSON_GENERATION: "LESSON_GENERATION",
  PASSAGE_GENERATION: "PASSAGE_GENERATION",
  HERO_VIDEO_MATCH: "HERO_VIDEO_MATCH",
  TDA_SCORING: "TDA_SCORING",
  GIST_GRADING: "GIST_GRADING",
  ESSAY_FEEDBACK: "ESSAY_FEEDBACK",
  MISCUE_CLASSIFICATION: "MISCUE_CLASSIFICATION",
  AUTOPILOT_PLAN: "AUTOPILOT_PLAN",
  AUTOPILOT_PROGRESSION: "AUTOPILOT_PROGRESSION",
  AUTOPILOT_INTERVENTION: "AUTOPILOT_INTERVENTION",
  PARENT_SUMMARY: "PARENT_SUMMARY",
  TUTOR_RECOMMENDATION: "TUTOR_RECOMMENDATION",
  AUTOPILOT_RATIONALE: "AUTOPILOT_RATIONALE",
  CONTENT_TAGGING: "CONTENT_TAGGING",
  CONTENT_FIRST_LOOK_REVIEW: "CONTENT_FIRST_LOOK_REVIEW",
  STANDARD_ALIGNMENT_CHECK: "STANDARD_ALIGNMENT_CHECK",
  TTS_GENERATION: "TTS_GENERATION",
} as const;

export type DecisionType = typeof DECISION_TYPES[keyof typeof DECISION_TYPES];
